// src/components/AnalyserVisualization.tsx
import { useRef, useEffect } from 'react';
import { createAnalyserEngine } from '../analyser-engine';
import type { AnalyserRuntime } from '../analyser-engine';

export type { AnalyserSource, AnalyserVariant, AnalyserMode, AnalyserScale, AnalyserSpring } from '../analyser-engine';
import type { AnalyserSource, AnalyserVariant, AnalyserMode, AnalyserScale, AnalyserSpring } from '../analyser-engine';

interface AnalyserVisualizationProps {
  /**
   * The Web Audio analyser to visualize. Purely observed — the component never
   * mutates it, so fftSize, smoothingTimeConstant, and the minDecibels..maxDecibels
   * window (which the byte data maps onto) stay under the host's control.
   */
  analyser?: AnalyserNode | null;
  /** 'frequency' — live spectrum (EQ-style). 'waveform' — time-domain oscilloscope. */
  source?: AnalyserSource;
  /** 'area' — translucent fill under the trace plus a crisp outline. 'line' — outline only. */
  variant?: AnalyserVariant;
  /**
   * 'smooth' — a simplified, interpolated trace. 'pixelated' — crisp, chunky
   * per-column blocks (the waveform visualizer's pixel language).
   */
  mode?: AnalyserMode;
  /**
   * Pixelated mode only: block-size multiplier. 1 (default) ≈ one CSS pixel per
   * column; 2 / 4 / 6 make progressively chunkier, lower-resolution columns.
   */
  pixelSize?: number;
  /** Frequency-axis spacing for the spectrum: 'log' (default, musical) or 'linear'. */
  scale?: AnalyserScale;
  /**
   * Spring-smooth the trace's movement (render-side; composes with the analyser's
   * own data-side smoothingTimeConstant — the spring can overshoot, that never does).
   * `true` for the default feel, or `{ stiffness, damping }` to tune it.
   */
  spring?: AnalyserSpring;
  /** Overlay a faint reference grid (vertical divisions) behind the trace. */
  grid?: boolean;
  /** Vertical divisions in the grid when `grid` is on (default 8). */
  gridSubdivisions?: number;
  /** Trace color. Defaults to the theme color. */
  waveColor?: string;
  /** Area-fill color (drawn translucent). Defaults to `waveColor`. */
  fillColor?: string;
  /**
   * Controlled mute state: dims the trace as feedback. The analyser is a passive
   * tap, so actually silencing the channel is the host's job (gain routing).
   */
  muted?: boolean;
  /** Shows the mute button; called with the requested state on click. */
  onMuteChange?: (muted: boolean) => void;
  /** Controlled solo state (cross-channel — the host owns what "solo" silences). */
  soloed?: boolean;
  /** Shows the solo button; called with the requested state on click. */
  onSoloChange?: (soloed: boolean) => void;
  width?: number;
  height?: number;
}

export function AnalyserVisualization({
  analyser = null,
  source = 'frequency',
  variant = 'area',
  mode = 'smooth',
  pixelSize = 1,
  scale = 'log',
  spring = false,
  grid = false,
  gridSubdivisions = 8,
  waveColor,
  fillColor,
  muted = false,
  onMuteChange,
  soloed = false,
  onSoloChange,
  width = 256,
  height = 140,
}: AnalyserVisualizationProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  // Latest props, read by the engine each frame so a prop change never restarts it.
  const runtimeRef = useRef<AnalyserRuntime>(null as unknown as AnalyserRuntime);
  runtimeRef.current = {
    analyser,
    source,
    variant,
    mode,
    pixelSize,
    scale,
    spring,
    grid,
    gridSubdivisions,
    waveColor,
    fillColor,
    muted,
    width,
    height,
  };

  useEffect(() => {
    if (!canvasRef.current) return;
    const engine = createAnalyserEngine(canvasRef.current, () => runtimeRef.current);
    return () => engine.destroy();
  }, []);

  return (
    <div className="dialkit-analyser-viz-wrap" style={{ width }}>
      <canvas ref={canvasRef} className="dialkit-analyser-viz" style={{ width, height }} />
      {(onMuteChange || onSoloChange) && (
        <div className="dialkit-analyser-actions">
          {onMuteChange && (
            <button type="button" aria-label="Mute" aria-pressed={muted} onClick={() => onMuteChange(!muted)}>
              <svg viewBox="0 0 16 16" fill="none">
                <path d="M3 6 H5 L8.5 3 V13 L5 10 H3 Z" fill="currentColor" />
                <path d="M10.5 6 L13.5 10 M13.5 6 L10.5 10" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
              </svg>
            </button>
          )}
          {onSoloChange && (
            <button type="button" aria-label="Solo" aria-pressed={soloed} onClick={() => onSoloChange(!soloed)}>
              <svg viewBox="0 0 16 16" fill="none">
                <path d="M3.4 12 V8.8 a4.6 4.6 0 0 1 9.2 0 V12" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
                <rect x="2.6" y="9.9" width="1.8" height="2.9" rx="0.9" fill="currentColor" />
                <rect x="11.6" y="9.9" width="1.8" height="2.9" rx="0.9" fill="currentColor" />
              </svg>
            </button>
          )}
        </div>
      )}
    </div>
  );
}

// src/solid/components/AnalyserVisualization.tsx
import { mergeProps, onCleanup, onMount, Show } from 'solid-js';
import { createAnalyserEngine } from '../../analyser-engine';
import type {
  AnalyserRuntime,
  AnalyserSource,
  AnalyserVariant,
  AnalyserMode,
  AnalyserScale,
  AnalyserSpring,
} from '../../analyser-engine';

export type { AnalyserSource, AnalyserVariant, AnalyserMode, AnalyserScale, AnalyserSpring } from '../../analyser-engine';

interface AnalyserVisualizationProps {
  analyser?: AnalyserNode | null;
  source?: AnalyserSource;
  variant?: AnalyserVariant;
  mode?: AnalyserMode;
  pixelSize?: number;
  scale?: AnalyserScale;
  spring?: AnalyserSpring;
  grid?: boolean;
  gridSubdivisions?: number;
  waveColor?: string;
  fillColor?: string;
  muted?: boolean;
  onMuteChange?: (muted: boolean) => void;
  soloed?: boolean;
  onSoloChange?: (soloed: boolean) => void;
  width?: number;
  height?: number;
}

export function AnalyserVisualization(props: AnalyserVisualizationProps) {
  const p = mergeProps(
    {
      analyser: null as AnalyserNode | null,
      source: 'frequency' as AnalyserSource,
      variant: 'area' as AnalyserVariant,
      mode: 'smooth' as AnalyserMode,
      pixelSize: 1,
      scale: 'log' as AnalyserScale,
      spring: false as AnalyserSpring,
      grid: false,
      gridSubdivisions: 8,
      muted: false,
      soloed: false,
      width: 256,
      height: 140,
    },
    props
  );

  let canvasEl: HTMLCanvasElement | undefined;

  onMount(() => {
    if (!canvasEl) return;
    const engine = createAnalyserEngine(
      canvasEl,
      (): AnalyserRuntime => ({
        analyser: p.analyser,
        source: p.source,
        variant: p.variant,
        mode: p.mode,
        pixelSize: p.pixelSize,
        scale: p.scale,
        spring: p.spring,
        grid: p.grid,
        gridSubdivisions: p.gridSubdivisions,
        waveColor: p.waveColor,
        fillColor: p.fillColor,
        muted: p.muted,
        width: p.width,
        height: p.height,
      })
    );
    onCleanup(() => engine.destroy());
  });

  return (
    <div class="dialkit-analyser-viz-wrap" style={{ width: `${p.width}px` }}>
      <canvas
        ref={canvasEl}
        class="dialkit-analyser-viz"
        style={{ width: `${p.width}px`, height: `${p.height}px` }}
      />
      <Show when={p.onMuteChange || p.onSoloChange}>
        <div class="dialkit-analyser-actions">
          <Show when={p.onMuteChange}>
            <button type="button" aria-label="Mute" aria-pressed={p.muted} onClick={() => p.onMuteChange?.(!p.muted)}>
              <svg viewBox="0 0 16 16" fill="none">
                <path d="M3 6 H5 L8.5 3 V13 L5 10 H3 Z" fill="currentColor" />
                <path d="M10.5 6 L13.5 10 M13.5 6 L10.5 10" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" />
              </svg>
            </button>
          </Show>
          <Show when={p.onSoloChange}>
            <button type="button" aria-label="Solo" aria-pressed={p.soloed} onClick={() => p.onSoloChange?.(!p.soloed)}>
              <svg viewBox="0 0 16 16" fill="none">
                <path d="M3.4 12 V8.8 a4.6 4.6 0 0 1 9.2 0 V12" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" />
                <rect x="2.6" y="9.9" width="1.8" height="2.9" rx="0.9" fill="currentColor" />
                <rect x="11.6" y="9.9" width="1.8" height="2.9" rx="0.9" fill="currentColor" />
              </svg>
            </button>
          </Show>
        </div>
      </Show>
    </div>
  );
}
