// src/components/ButtonGroup.tsx
interface ButtonGroupProps {
  buttons: Array<{
    label: string;
    onClick: () => void;
  }>;
}

export function ButtonGroup({ buttons }: ButtonGroupProps) {
  return (
    <div className="tweakers-button-group">
      {buttons.map((button, index) => (
        <button
          key={index}
          className="tweakers-button"
          onClick={button.onClick}
        >
          {button.label}
        </button>
      ))}
    </div>
  );
}

// src/solid/components/ButtonGroup.tsx
import { For } from 'solid-js';

interface ButtonGroupProps {
  buttons: Array<{
    label: string;
    onClick: () => void;
  }>;
}

export function ButtonGroup(props: ButtonGroupProps) {
  return (
    <div class="tweakers-button-group">
      <For each={props.buttons}>
        {(button) => (
          <button class="tweakers-button" onClick={button.onClick}>
            {button.label}
          </button>
        )}
      </For>
    </div>
  );
}
