// src/svelte/components/Folder.svelte
<script lang="ts">
  import { Spring } from 'svelte/motion';
  import { slide } from 'svelte/transition';

  import type { Snippet } from 'svelte';
  import { ICON_PANEL, ICON_CHEVRON } from 'tweakers/icons';
  import Checkbox from './Checkbox.svelte';

  let {
    title,
    defaultOpen = true,
    collapsible = true,
    isRoot = false,
    inline = false,
    onOpenChange,
    toolbar,
    children,
    hint,
    hintId,
    enabled = undefined,
    onEnabledChange = undefined,
  } = $props<{
    title: string;
    defaultOpen?: boolean;
    /** `false` renders a plain section header: no caret, no click-to-collapse, body always open. */
    collapsible?: boolean;
    isRoot?: boolean;
    inline?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
    toolbar?: Snippet;
    children?: Snippet;
    /** One line of help for the section, revealed on hover over the header. */
    hint?: string;
    hintId?: string;
    /**
     * Root only — the panel declared `_enabled`, so the whole panel is a
     * module: the title carries the switch and the body goes away when it is
     * off. Same idiom as ModuleFolder, one level up.
     */
    enabled?: boolean;
    onEnabledChange?: (enabled: boolean) => void;
  }>();


  let isOpen = $state(collapsible ? defaultOpen : true);
  // A module panel's switch is the only thing that shows or hides its body —
  // the rows below the title belong to a feature that is either on or off.
  const isModule = $derived(isRoot && enabled !== undefined && onEnabledChange !== undefined);
  const bodyOpen = $derived(isOpen && (!isModule || !!enabled));
  let isCollapsed = $state(collapsible ? !defaultOpen : false);
  let contentHeight = $state<number | undefined>(undefined);

  let contentRef: HTMLDivElement | undefined;
  let panelRef: HTMLDivElement | undefined;
  let windowHeight = $state(typeof window !== 'undefined' ? window.innerHeight : 800);

  $effect(() => {
    if (!isRoot) return;
    const onResize = () => { windowHeight = window.innerHeight; };
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  });

  const chevronRotation = new Spring(defaultOpen ? 0 : 180, { stiffness: 0.2, damping: 0.6 });
  const panelWidth = new Spring(defaultOpen ? 280 : 42, { stiffness: 0.2, damping: 0.62 });
  const panelHeight = new Spring(defaultOpen ? 220 : 42, { stiffness: 0.2, damping: 0.62 });
  const panelRadius = new Spring(defaultOpen ? 14 : 21, { stiffness: 0.2, damping: 0.62 });
  const panelScale = new Spring(1, { stiffness: 0.25, damping: 0.7 });

  $effect(() => {
    if (!isRoot || !contentRef || typeof ResizeObserver === 'undefined') return;

    const ro = new ResizeObserver(() => {
      if (!isOpen) return;
      const next = contentRef?.offsetHeight;
      if (!next) return;
      contentHeight = next;
    });

    ro.observe(contentRef);

    if (contentRef.offsetHeight > 0) {
      contentHeight = contentRef.offsetHeight;
    }

    return () => {
      ro.disconnect();
    };
  });

  $effect(() => {
    if (isRoot) return;
    chevronRotation.set(isOpen ? 0 : 180);
  });

  $effect(() => {
    if (!isRoot) return;

    const measured = contentHeight ?? panelRef?.getBoundingClientRect().height ?? 42;
    const nextHeight = isOpen ? Math.min(measured + 10, windowHeight - 32) : 42;

    panelWidth.set(isOpen ? 280 : 42);
    panelHeight.set(nextHeight);
    panelRadius.set(isOpen ? 14 : 21);
  });

  const handleToggle = () => {
    if (!collapsible) return;
    if (inline && isRoot) return;
    const next = !isOpen;
    isOpen = next;
    isCollapsed = !next;
    onOpenChange?.(next);
  };

  const handleCollapsedTapStart = () => {
    if (isOpen) return;
    (document.activeElement as HTMLElement | null)?.blur?.();
    panelScale.set(0.9);
  };

  const handleCollapsedTapEnd = () => {
    if (isOpen) return;
    panelScale.set(1);
  };

  const panelStyle = $derived(
    `width:${panelWidth.current}px;height:${panelHeight.current}px;border-radius:${panelRadius.current}px;` +
      `box-shadow:${isOpen ? 'var(--tweak-shadow)' : 'var(--tweak-shadow-collapsed)'};` +
      `cursor:${isOpen ? '' : 'pointer'};overflow:${isOpen ? 'hidden auto' : 'hidden'};` +
      `transform:scale(${panelScale.current});`
  );
</script>

{#if isRoot && inline}
  <div class="tweakers-panel-inner tweakers-panel-inline">
    <div bind:this={contentRef} class="tweakers-folder tweakers-folder-root">
      <div class="tweakers-folder-header tweakers-panel-header" onclick={(e) => { e.stopPropagation(); handleToggle(); }}>
        <div class="tweakers-folder-header-top">
          <div class="tweakers-folder-title-row">
            {#if isModule}
              <Checkbox checked={!!enabled} onChange={onEnabledChange!} label={title} />
            {/if}
            <span class="tweakers-folder-title tweakers-folder-title-root">{title}</span>
          </div>
        </div>

        <div class="tweakers-panel-toolbar" onclick={(e) => e.stopPropagation()}>
          {#if toolbar}{@render toolbar()}{/if}
        </div>
      </div>

      {#if bodyOpen}
      <div class="tweakers-folder-content">
        <div class="tweakers-folder-inner">
          {#if children}{@render children()}{/if}
        </div>
      </div>
      {/if}
    </div>
  </div>
{:else if isRoot}
  <div
    bind:this={panelRef}
    class="tweakers-panel-inner"
    data-collapsed={String(isCollapsed)}
    style={panelStyle}
    onpointerdown={handleCollapsedTapStart}
    onpointerup={handleCollapsedTapEnd}
    onpointercancel={handleCollapsedTapEnd}
    onpointerleave={handleCollapsedTapEnd}
    onclick={() => { if (!isOpen) handleToggle(); }}
  >
    <div bind:this={contentRef} class="tweakers-folder tweakers-folder-root">
      <div class="tweakers-folder-header tweakers-panel-header" onclick={(e) => { e.stopPropagation(); handleToggle(); }}>
        <div class="tweakers-folder-header-top">
          {#if isOpen}
            <div class="tweakers-folder-title-row">
              {#if isModule}
                <Checkbox checked={!!enabled} onChange={onEnabledChange!} label={title} />
              {/if}
              <span class="tweakers-folder-title tweakers-folder-title-root">{title}</span>
            </div>
          {/if}

          <svg class="tweakers-panel-icon" viewBox="0 0 16 16" fill="none">
            <path
              opacity="0.5"
              d={ICON_PANEL.path}
              fill="currentColor"
            />
            <circle cx={ICON_PANEL.circles[0].cx} cy={ICON_PANEL.circles[0].cy} r={ICON_PANEL.circles[0].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
            <circle cx={ICON_PANEL.circles[1].cx} cy={ICON_PANEL.circles[1].cy} r={ICON_PANEL.circles[1].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
            <circle cx={ICON_PANEL.circles[2].cx} cy={ICON_PANEL.circles[2].cy} r={ICON_PANEL.circles[2].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
          </svg>
        </div>

        {#if isOpen}
          <div class="tweakers-panel-toolbar" onclick={(e) => e.stopPropagation()}>
            {#if toolbar}{@render toolbar()}{/if}
          </div>
        {/if}
      </div>

      {#if bodyOpen}
        <div class="tweakers-folder-content">
          <div class="tweakers-folder-inner">
            {#if children}{@render children()}{/if}
          </div>
        </div>
      {/if}
    </div>
  </div>
{:else}
  <div class="tweakers-folder">
    <div
      class="tweakers-folder-header {collapsible ? '' : 'tweakers-folder-header-static'}"
      onclick={collapsible ? handleToggle : undefined}
      data-hint={hint ? 'true' : undefined}
      aria-describedby={hint ? hintId : undefined}
    >
      <div class="tweakers-folder-header-top">
        <div class="tweakers-folder-title-row">
          <span class="tweakers-folder-title">{title}</span>
        </div>

        {#if collapsible}
        <svg
          class="tweakers-folder-icon"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.5"
          stroke-linecap="round"
          stroke-linejoin="round"
          style:transform={`rotate(${chevronRotation.current}deg)`}
        >
          <path d={ICON_CHEVRON} />
        </svg>
        {/if}
      </div>

      {#if hint}
        <span class="tweakers-hint" id={hintId} role="tooltip">{hint}</span>
      {/if}
    </div>

    {#if isOpen}
      <div class="tweakers-folder-content" style="clip-path: inset(0 -20px);" transition:slide={{ duration: 220 }}>
        <div class="tweakers-folder-inner">
          {#if children}{@render children()}{/if}
        </div>
      </div>
    {/if}
  </div>
{/if}

// src/solid/components/Folder.tsx
import { createSignal, createEffect, onCleanup, Show, JSX } from 'solid-js';
import { animate } from 'motion';
import { ICON_PANEL, ICON_CHEVRON } from 'tweakers/icons';
import { Checkbox } from './Checkbox';

interface FolderProps {
  title: string;
  children: JSX.Element;
  defaultOpen?: boolean;
  /** `false` renders a plain section header: no caret, no click-to-collapse, body always open. */
  collapsible?: boolean;
  isRoot?: boolean;
  inline?: boolean;
  onOpenChange?: (isOpen: boolean) => void;
  toolbar?: JSX.Element;
  /** One line of help for the section, revealed on hover over the header. */
  hint?: string;
  hintId?: string;
  /**
   * Root only — the panel declared `_enabled`, so the whole panel is a module:
   * the title carries the switch and the body goes away when it is off. Same
   * idiom as ModuleFolder, one level up.
   */
  enabled?: boolean;
  onEnabledChange?: (enabled: boolean) => void;
}

export function Folder(props: FolderProps) {
  const [isOpen, setIsOpen] = createSignal(props.defaultOpen ?? true);
  const [isCollapsed, setIsCollapsed] = createSignal(!(props.defaultOpen ?? true));
  const [contentHeight, setContentHeight] = createSignal<number | undefined>(undefined);
  const [windowHeight, setWindowHeight] = createSignal(typeof window !== 'undefined' ? window.innerHeight : 800);

  // A module panel's switch is the only thing that shows or hides its body —
  // the rows below the title belong to a feature that is either on or off.
  const isModule = () =>
    !!props.isRoot && props.enabled !== undefined && props.onEnabledChange !== undefined;
  const bodyOpen = () => isOpen() && (!isModule() || !!props.enabled);

  if (props.isRoot) {
    const onResize = () => setWindowHeight(window.innerHeight);
    window.addEventListener('resize', onResize);
    onCleanup(() => window.removeEventListener('resize', onResize));
  }

  // Section content animation state
  const [contentMounted, setContentMounted] = createSignal(props.defaultOpen ?? true);
  let skipFirstAnim = props.defaultOpen ?? true;
  let sectionContentRef: HTMLDivElement | undefined;
  let sectionAnim: any = null;
  let folderChevronRef: SVGSVGElement | undefined;
  let chevronAnim: any = null;
  let chevronInitialized = false;
  let panelTapAnim: any = null;

  let contentRef: HTMLDivElement | undefined;

  // Track content height for root panel sizing
  createEffect(() => {
    if (!props.isRoot || !isOpen()) return;
    const el = contentRef;
    if (!el) return;
    const ro = new ResizeObserver(() => {
      const h = el.offsetHeight;
      setContentHeight(prev => prev === h ? prev : h);
    });
    ro.observe(el);
    onCleanup(() => ro.disconnect());
  });

  createEffect(() => {
    if (props.isRoot || !folderChevronRef) return;
    const open = isOpen();
    chevronAnim?.stop();

    if (!chevronInitialized) {
      folderChevronRef.style.transform = `rotate(${open ? 0 : 180}deg)`;
      chevronInitialized = true;
      return;
    }

    chevronAnim = animate(
      folderChevronRef,
      { rotate: open ? 0 : 180 },
      { type: 'spring', visualDuration: 0.35, bounce: 0.15 }
    );

    onCleanup(() => chevronAnim?.stop());
  });

  const handleToggle = () => {
    if (props.collapsible === false) return;
    if (props.inline && props.isRoot) return;
    const next = !isOpen();
    setIsOpen(next);
    if (next) {
      setIsCollapsed(false);
      if (!props.isRoot) {
        sectionAnim?.stop();
        sectionAnim = null;
        if (sectionContentRef) {
          // If close was interrupted, animate section back open.
          sectionAnim = animate(
            sectionContentRef,
            { height: 'auto', opacity: 1 },
            {
              type: 'spring',
              visualDuration: 0.35,
              bounce: 0.1,
              onComplete: () => {
                sectionAnim = null;
              },
            }
          );
        } else {
          // If fully unmounted, mount and let the ref callback run enter animation.
          setContentMounted(true);
        }
      }
    } else {
      setIsCollapsed(true);
      if (!props.isRoot) {
        if (sectionContentRef) {
          const currentHeight = sectionContentRef.getBoundingClientRect().height;
          sectionContentRef.style.height = `${currentHeight}px`;
          sectionAnim?.stop();
          sectionAnim = animate(
            sectionContentRef,
            { height: 0, opacity: 0 },
            {
              type: 'spring', visualDuration: 0.35, bounce: 0.1,
              onComplete: () => {
                setContentMounted(false);
                sectionAnim = null;
                sectionContentRef = undefined;
              },
            }
          );
        } else {
          setContentMounted(false);
        }
      }
    }
    props.onOpenChange?.(next);
  };

  const folderContent = () => (
    <div
      ref={(el) => { if (props.isRoot) contentRef = el; }}
      class={`tweakers-folder ${props.isRoot ? 'tweakers-folder-root' : ''}`}
    >
      <div
        class={`tweakers-folder-header ${props.isRoot ? 'tweakers-panel-header' : ''} ${props.collapsible === false ? 'tweakers-folder-header-static' : ''}`}
        onClick={props.collapsible === false ? undefined : handleToggle}
        data-hint={props.hint ? 'true' : undefined}
        aria-describedby={props.hint ? props.hintId : undefined}
      >
        <div class="tweakers-folder-header-top">
          {props.isRoot ? (
            <Show when={isOpen()}>
              <div class="tweakers-folder-title-row">
                <Show when={isModule()}>
                  <Checkbox
                    checked={props.enabled!}
                    onChange={props.onEnabledChange!}
                    label={props.title}
                  />
                </Show>
                <span class="tweakers-folder-title tweakers-folder-title-root">
                  {props.title}
                </span>
              </div>
            </Show>
          ) : (
            <div class="tweakers-folder-title-row">
              <span class="tweakers-folder-title">{props.title}</span>
            </div>
          )}

          {props.isRoot && !props.inline && (
            <svg class="tweakers-panel-icon" viewBox="0 0 16 16" fill="none">
              <path
                opacity="0.5"
                d={ICON_PANEL.path}
                fill="currentColor"
              />
              <circle cx={ICON_PANEL.circles[0].cx} cy={ICON_PANEL.circles[0].cy} r={ICON_PANEL.circles[0].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
              <circle cx={ICON_PANEL.circles[1].cx} cy={ICON_PANEL.circles[1].cy} r={ICON_PANEL.circles[1].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
              <circle cx={ICON_PANEL.circles[2].cx} cy={ICON_PANEL.circles[2].cy} r={ICON_PANEL.circles[2].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
            </svg>
          )}
          {!props.isRoot && props.collapsible !== false && (
            <svg
              ref={folderChevronRef}
              class="tweakers-folder-icon"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2.5"
              stroke-linecap="round"
              stroke-linejoin="round"
            >
              <path d={ICON_CHEVRON} />
            </svg>
          )}
        </div>

        <Show when={props.isRoot && props.toolbar && isOpen()}>
          <div class="tweakers-panel-toolbar" onClick={(e) => e.stopPropagation()}>
            {props.toolbar}
          </div>
        </Show>

        <Show when={props.hint}>
          <span class="tweakers-hint" id={props.hintId} role="tooltip">
            {props.hint}
          </span>
        </Show>
      </div>

      <Show when={props.isRoot ? bodyOpen() : contentMounted()}>
        <div
          ref={(el) => {
            if (props.isRoot) return;
            sectionContentRef = el;
            if (skipFirstAnim) { skipFirstAnim = false; return; }

            sectionAnim?.stop();
            el.style.height = '0px';
            el.style.opacity = '0';
            sectionAnim = animate(
              el,
              { height: 'auto', opacity: 1 },
              {
                type: 'spring',
                visualDuration: 0.35,
                bounce: 0.1,
                onComplete: () => {
                  sectionAnim = null;
                },
              }
            );
          }}
          class="tweakers-folder-content"
          style={!props.isRoot ? { 'clip-path': 'inset(0 -20px)' } : undefined}
        >
          <div class="tweakers-folder-inner">{props.children}</div>
        </div>
      </Show>
    </div>
  );

  if (props.isRoot) {
    if (props.inline) {
      return (
        <div class="tweakers-panel-inner tweakers-panel-inline">
          {folderContent()}
        </div>
      );
    }
    let panelRef!: HTMLDivElement;
    let rootPanelAnim: any = null;
    let rootPanelInitialized = false;
    let lastRootOpen = isOpen();

    createEffect(() => {
      if (!panelRef || isOpen()) return;
      const handler = (e: Event) => {
        e.stopPropagation();
        handleToggle();
      };
      panelRef.addEventListener('click', handler);
      onCleanup(() => panelRef.removeEventListener('click', handler));
    });

    createEffect(() => {
      if (!panelRef) return;

      const open = isOpen();
      const measuredOpenHeight = contentHeight() !== undefined
        ? Math.min(contentHeight()! + 10, windowHeight() - 32)
        : panelRef.getBoundingClientRect().height;

      const target = {
        width: open ? 280 : 42,
        height: open ? measuredOpenHeight : 42,
        borderRadius: open ? 14 : 21,
        boxShadow: open
          ? 'var(--tweak-shadow)'
          : 'var(--tweak-shadow-collapsed)',
      };

      panelRef.style.cursor = open ? '' : 'pointer';
      panelRef.style.overflow = open ? 'hidden auto' : 'hidden';

      if (!rootPanelInitialized) {
        rootPanelInitialized = true;
        panelRef.style.width = `${target.width}px`;
        panelRef.style.height = `${target.height}px`;
        panelRef.style.borderRadius = `${target.borderRadius}px`;
        panelRef.style.boxShadow = target.boxShadow;
        lastRootOpen = open;
        return;
      }

      if (open !== lastRootOpen) {
        rootPanelAnim?.stop();
        rootPanelAnim = animate(panelRef, target, {
          type: 'spring',
          visualDuration: 0.15,
          bounce: 0.3,
          onComplete: () => {
            rootPanelAnim = null;
          },
        });
        lastRootOpen = open;
        return;
      }

      if (open) {
        panelRef.style.height = `${target.height}px`;
      }
    });

    onCleanup(() => {
      rootPanelAnim?.stop();
      panelTapAnim?.stop();
    });

    return (
      <div
        ref={panelRef}
        class="tweakers-panel-inner"
        data-collapsed={String(isCollapsed())}
        onPointerDown={() => {
          if (isOpen()) return;
          (document.activeElement as HTMLElement)?.blur?.();
          panelTapAnim?.stop();
          panelTapAnim = animate(panelRef, { scale: 0.9 }, { type: 'spring', visualDuration: 0.15, bounce: 0.3 });
        }}
        onPointerUp={() => {
          if (isOpen()) return;
          panelTapAnim?.stop();
          panelTapAnim = animate(panelRef, { scale: 1 }, { type: 'spring', visualDuration: 0.15, bounce: 0.3 });
        }}
        onPointerCancel={() => {
          if (isOpen()) return;
          panelTapAnim?.stop();
          panelTapAnim = animate(panelRef, { scale: 1 }, { type: 'spring', visualDuration: 0.15, bounce: 0.3 });
        }}
        onPointerLeave={() => {
          if (isOpen()) return;
          panelTapAnim?.stop();
          panelTapAnim = animate(panelRef, { scale: 1 }, { type: 'spring', visualDuration: 0.15, bounce: 0.3 });
        }}
      >
        {folderContent()}
      </div>
    );
  }

  return folderContent();
}
