// src/components/TransitionControl.tsx
import { SpringConfig, EasingConfig, TransitionConfig, TweakStore } from 'tweakers/store';
import { Folder } from './Folder';
import { Slider } from './Slider';
import { SegmentedControl } from './SegmentedControl';
import { SpringVisualization } from './SpringVisualization';
import { EasingVisualization } from './EasingVisualization';
import { useSyncExternalStore, useRef, useState } from 'react';

interface TransitionControlProps {
  panelId: string;
  path: string;
  label: string;
  value: TransitionConfig;
  onChange: (value: TransitionConfig) => void;
  /** Hide duration sliders when something else owns the duration (e.g. a timeline clip bar). */
  hideDuration?: boolean;
  /** Route duration edits through an external owner while keeping this control's layout. */
  durationControl?: {
    value: number;
    onChange: (value: number) => void;
    min?: number;
    max?: number;
    step?: number;
  };
}

type CurveMode = 'easing' | 'simple' | 'advanced';

export function TransitionControl({
  panelId,
  path,
  label,
  value,
  onChange,
  hideDuration = false,
  durationControl,
}: TransitionControlProps) {
  const mode = useSyncExternalStore(
    (cb) => TweakStore.subscribe(panelId, cb),
    () => TweakStore.getTransitionMode(panelId, path),
    () => TweakStore.getTransitionMode(panelId, path)
  );

  const isEasing = mode === 'easing';
  const isSimpleSpring = mode === 'simple';

  // Cache per-mode values so switching back restores previous edits
  const cache = useRef<{
    easing: EasingConfig;
    simple: SpringConfig;
    advanced: SpringConfig;
  }>({
    easing: value.type === 'easing' ? value : { type: 'easing', duration: 0.3, ease: [1, -0.4, 0.5, 1] },
    simple: value.type === 'spring' && value.visualDuration !== undefined ? value : { type: 'spring', visualDuration: 0.3, bounce: 0.2 },
    advanced: value.type === 'spring' && value.stiffness !== undefined ? value : { type: 'spring', stiffness: 200, damping: 25, mass: 1 },
  });

  // Keep cache up to date with current edits
  if (isEasing && value.type === 'easing') {
    cache.current.easing = value;
  } else if (isSimpleSpring && value.type === 'spring') {
    cache.current.simple = value;
  } else if (mode === 'advanced' && value.type === 'spring') {
    cache.current.advanced = value;
  }

  const spring: SpringConfig = value.type === 'spring' ? value : cache.current.simple;
  const easing: EasingConfig = value.type === 'easing' ? value : cache.current.easing;

  const handleModeChange = (newMode: CurveMode) => {
    TweakStore.updateTransitionMode(panelId, path, newMode);

    if (newMode === 'easing') {
      onChange(cache.current.easing);
    } else if (newMode === 'simple') {
      onChange(cache.current.simple);
    } else {
      onChange(cache.current.advanced);
    }
  };

  const handleSpringUpdate = (key: keyof SpringConfig, val: number) => {
    if (isSimpleSpring) {
      const { stiffness, damping, mass, ...rest } = spring;
      onChange({ ...rest, [key]: val });
    } else {
      const { visualDuration, bounce, ...rest } = spring;
      onChange({ ...rest, [key]: val });
    }
  };

  const updateEase = (index: number, val: number) => {
    const newEase = [...easing.ease] as [number, number, number, number];
    newEase[index] = val;
    onChange({ ...easing, ease: newEase });
  };

  const durationSlider = !hideDuration && (isEasing || isSimpleSpring) ? (
    <Slider
      label="Duration"
      value={durationControl?.value ?? (isEasing ? easing.duration : spring.visualDuration ?? 0.3)}
      onChange={durationControl?.onChange ?? ((next) => {
        if (isEasing) onChange({ ...easing, duration: next });
        else handleSpringUpdate('visualDuration', next);
      })}
      min={durationControl?.min ?? 0.1}
      max={durationControl?.max ?? (isEasing ? 2 : 1)}
      step={durationControl?.step ?? 0.05}
      unit="s"
    />
  ) : null;

  return (
    <Folder title={label} defaultOpen={true}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
        {isEasing ? (
          <EasingVisualization easing={easing} />
        ) : (
          <SpringVisualization spring={spring} isSimpleMode={isSimpleSpring} />
        )}

        <div className="tweakers-labeled-control">
          <span className="tweakers-labeled-control-label">Type</span>
          <SegmentedControl
            options={[
              { value: 'easing' as const, label: 'Easing' },
              { value: 'simple' as const, label: 'Time' },
              { value: 'advanced' as const, label: 'Physics' },
            ]}
            value={mode}
            onChange={handleModeChange}
          />
        </div>

        {isEasing ? (
          <>
            <Slider label="x1" value={easing.ease[0]} onChange={(v) => updateEase(0, v)} min={0} max={1} step={0.01} />
            <Slider label="y1" value={easing.ease[1]} onChange={(v) => updateEase(1, v)} min={-1} max={2} step={0.01} />
            <Slider label="x2" value={easing.ease[2]} onChange={(v) => updateEase(2, v)} min={0} max={1} step={0.01} />
            <Slider label="y2" value={easing.ease[3]} onChange={(v) => updateEase(3, v)} min={-1} max={2} step={0.01} />
            <EaseTextInput ease={easing.ease} onChange={(newEase) => onChange({ ...easing, ease: newEase })} />
          </>
        ) : isSimpleSpring ? (
          <Slider label="Bounce" value={spring.bounce ?? 0.2} onChange={(v) => handleSpringUpdate('bounce', v)} min={0} max={1} step={0.05} />
        ) : (
          <>
            <Slider label="Stiffness" value={spring.stiffness ?? 400} onChange={(v) => handleSpringUpdate('stiffness', v)} min={1} max={1000} step={10} />
            <Slider label="Damping" value={spring.damping ?? 17} onChange={(v) => handleSpringUpdate('damping', v)} min={1} max={100} step={1} />
            <Slider label="Mass" value={spring.mass ?? 1} onChange={(v) => handleSpringUpdate('mass', v)} min={0.1} max={10} step={0.1} />
          </>
        )}
        {durationSlider}
      </div>
    </Folder>
  );
}

function formatEase(ease: [number, number, number, number]): string {
  return ease.map(v => parseFloat(v.toFixed(2))).join(', ');
}

function parseEase(str: string): [number, number, number, number] | null {
  const parts = str.split(',').map(s => parseFloat(s.trim()));
  if (parts.length === 4 && parts.every(n => !isNaN(n))) {
    return parts as [number, number, number, number];
  }
  return null;
}

function EaseTextInput({ ease, onChange }: { ease: [number, number, number, number]; onChange: (ease: [number, number, number, number]) => void }) {
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState('');

  const handleFocus = () => {
    setDraft(formatEase(ease));
    setEditing(true);
  };

  const handleBlur = () => {
    const parsed = parseEase(draft);
    if (parsed) onChange(parsed);
    setEditing(false);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      (e.target as HTMLInputElement).blur();
    }
  };

  return (
    <div className="tweakers-labeled-control">
      <span className="tweakers-labeled-control-label">Ease</span>
      <input
        type="text"
        className="tweakers-text-input"
        value={editing ? draft : formatEase(ease)}
        onChange={(e) => setDraft(e.target.value)}
        onFocus={handleFocus}
        onBlur={handleBlur}
        onKeyDown={handleKeyDown}
        spellCheck={false}
      />
    </div>
  );
}

// src/solid/components/TransitionControl.tsx
import { createSignal, Show } from 'solid-js';
import { TweakStore } from 'tweakers/store';
import type { EasingConfig, SpringConfig, TransitionConfig } from 'tweakers/store';
import { fromStore } from '../primitives';
import { EasingVisualization } from './EasingVisualization';
import { Folder } from './Folder';
import { SegmentedControl } from './SegmentedControl';
import { Slider } from './Slider';
import { SpringVisualization } from './SpringVisualization';

export interface TransitionDurationControl {
  value: number;
  onChange: (value: number) => void;
  min?: number;
  max?: number;
  step?: number;
}

interface TransitionControlProps {
  panelId: string;
  path: string;
  label: string;
  value: TransitionConfig;
  onChange: (value: TransitionConfig) => void;
  hideDuration?: boolean;
  durationControl?: TransitionDurationControl;
}

type CurveMode = 'easing' | 'simple' | 'advanced';

export function TransitionControl(props: TransitionControlProps) {
  const mode = fromStore(
    () => TweakStore.getTransitionMode(props.panelId, props.path),
    (notify) => TweakStore.subscribe(props.panelId, notify)
  );
  const [editingEase, setEditingEase] = createSignal(false);
  const [easeDraft, setEaseDraft] = createSignal('');
  const cache: { easing: EasingConfig; simple: SpringConfig; advanced: SpringConfig } = {
    easing: props.value.type === 'easing'
      ? props.value
      : { type: 'easing', duration: 0.3, ease: [1, -0.4, 0.5, 1] },
    simple: props.value.type === 'spring' && props.value.visualDuration !== undefined
      ? props.value
      : { type: 'spring', visualDuration: 0.3, bounce: 0.2 },
    advanced: props.value.type === 'spring' && props.value.stiffness !== undefined
      ? props.value
      : { type: 'spring', stiffness: 200, damping: 25, mass: 1 },
  };

  const isEasing = () => mode() === 'easing';
  const isSimple = () => mode() === 'simple';
  const spring = () => {
    if (props.value.type === 'spring') {
      if (isSimple()) cache.simple = props.value;
      else if (mode() === 'advanced') cache.advanced = props.value;
      return props.value;
    }
    return cache.simple;
  };
  const easing = () => {
    if (props.value.type === 'easing') {
      cache.easing = props.value;
      return props.value;
    }
    return cache.easing;
  };

  const handleModeChange = (next: CurveMode) => {
    TweakStore.updateTransitionMode(props.panelId, props.path, next);
    props.onChange(next === 'easing' ? cache.easing : next === 'simple' ? cache.simple : cache.advanced);
  };

  const handleSpringUpdate = (key: keyof SpringConfig, value: number) => {
    const current = spring();
    if (isSimple()) {
      const { stiffness, damping, mass, ...rest } = current;
      props.onChange({ ...rest, [key]: value });
    } else {
      const { visualDuration, bounce, ...rest } = current;
      props.onChange({ ...rest, [key]: value });
    }
  };

  const updateEase = (index: number, value: number) => {
    const current = easing();
    const next = [...current.ease] as [number, number, number, number];
    next[index] = value;
    props.onChange({ ...current, ease: next });
  };

  const formatEase = (value: [number, number, number, number]) =>
    value.map((part) => Number(part.toFixed(2))).join(', ');
  const commitEase = () => {
    const parts = easeDraft().split(',').map((part) => Number.parseFloat(part.trim()));
    if (parts.length === 4 && parts.every(Number.isFinite)) {
      props.onChange({ ...easing(), ease: parts as [number, number, number, number] });
    }
    setEditingEase(false);
  };

  const durationSlider = () => {
    if (props.hideDuration || (!isEasing() && !isSimple())) return null;
    const external = props.durationControl;
    return (
      <Slider
        label="Duration"
        value={external?.value ?? (isEasing() ? easing().duration : spring().visualDuration ?? 0.3)}
        onChange={external?.onChange ?? ((value) => {
          if (isEasing()) props.onChange({ ...easing(), duration: value });
          else handleSpringUpdate('visualDuration', value);
        })}
        min={external?.min ?? 0.1}
        max={external?.max ?? (isEasing() ? 2 : 1)}
        step={external?.step ?? 0.05}
        unit="s"
      />
    );
  };

  return (
    <Folder title={props.label} defaultOpen={true}>
      <div style={{ display: 'flex', 'flex-direction': 'column', gap: '6px' }}>
        <Show when={isEasing()} fallback={<SpringVisualization spring={spring()} isSimpleMode={isSimple()} />}>
          <EasingVisualization easing={easing()} />
        </Show>

        <div class="tweakers-labeled-control">
          <span class="tweakers-labeled-control-label">Type</span>
          <SegmentedControl
            options={[
              { value: 'easing', label: 'Easing' },
              { value: 'simple', label: 'Time' },
              { value: 'advanced', label: 'Physics' },
            ]}
            value={mode()}
            onChange={handleModeChange}
          />
        </div>

        <Show when={isEasing()}>
          <Slider label="x1" value={easing().ease[0]} onChange={(value) => updateEase(0, value)} min={0} max={1} step={0.01} />
          <Slider label="y1" value={easing().ease[1]} onChange={(value) => updateEase(1, value)} min={-1} max={2} step={0.01} />
          <Slider label="x2" value={easing().ease[2]} onChange={(value) => updateEase(2, value)} min={0} max={1} step={0.01} />
          <Slider label="y2" value={easing().ease[3]} onChange={(value) => updateEase(3, value)} min={-1} max={2} step={0.01} />
          <div class="tweakers-labeled-control">
            <span class="tweakers-labeled-control-label">Ease</span>
            <input
              type="text"
              class="tweakers-text-input"
              value={editingEase() ? easeDraft() : formatEase(easing().ease)}
              onInput={(event) => setEaseDraft(event.currentTarget.value)}
              onFocus={() => {
                setEaseDraft(formatEase(easing().ease));
                setEditingEase(true);
              }}
              onBlur={commitEase}
              onKeyDown={(event) => {
                if (event.key === 'Enter') event.currentTarget.blur();
              }}
              spellcheck={false}
            />
          </div>
        </Show>

        <Show when={isSimple()}>
          <Slider label="Bounce" value={spring().bounce ?? 0.2} onChange={(value) => handleSpringUpdate('bounce', value)} min={0} max={1} step={0.05} />
        </Show>
        <Show when={!isEasing() && !isSimple()}>
          <Slider label="Stiffness" value={spring().stiffness ?? 400} onChange={(value) => handleSpringUpdate('stiffness', value)} min={1} max={1000} step={10} />
          <Slider label="Damping" value={spring().damping ?? 17} onChange={(value) => handleSpringUpdate('damping', value)} min={1} max={100} step={1} />
          <Slider label="Mass" value={spring().mass ?? 1} onChange={(value) => handleSpringUpdate('mass', value)} min={0.1} max={10} step={0.1} />
        </Show>
        {durationSlider()}
      </div>
    </Folder>
  );
}
