// src/solid/components/ColorPickerPanel.tsx
import { createSignal, createEffect, onCleanup, Show, For } from 'solid-js';
import { SegmentedControl } from './SegmentedControl';
import {
  parseHex,
  formatHex,
  normalizeHex,
  rgbToHsv,
  hsvToRgb,
  getChannels,
  rgbaToChannels,
  channelsToRgba,
  opacityPercent,
  emptyPalette,
  LONG_PRESS_MS,
  PALETTE_DRAG_CANCEL_PX,
  PALETTE_SIZE,
  type ColorFormat,
  type HSVA,
  type ChannelSpec,
  type PaletteSlots,
} from 'tweakers/color-core';
import { loadPalette, savePalette, subscribePalette } from 'tweakers/color-palette-store';

interface ColorPickerPanelProps {
  value: string;
  onChange: (value: string) => void;
  alpha?: boolean;
  palette?: boolean;
}

const FORMAT_OPTIONS: { value: ColorFormat; label: string }[] = [
  { value: 'hex', label: 'HEX' },
  { value: 'rgb', label: 'RGB' },
  { value: 'hsl', label: 'HSL' },
  { value: 'oklch', label: 'OKLCH' },
];

// The format choice follows the user across pickers within a session —
// switching to OKLCH once shouldn't need repeating per control.
let stickyFormat: ColorFormat = 'hex';

const BLACK: HSVA = { h: 0, s: 0, v: 0, a: 1 };

/** Shared drag surface: pointer-capture + normalized 0–1 coordinates. */
function createAreaDrag(onPoint: (x: number, y: number) => void) {
  let el: HTMLDivElement | undefined;
  let dragging = false;

  const readPoint = (e: PointerEvent) => {
    if (!el) return;
    const rect = el.getBoundingClientRect();
    const x = Math.min(1, Math.max(0, (e.clientX - rect.left) / rect.width));
    const y = Math.min(1, Math.max(0, (e.clientY - rect.top) / rect.height));
    onPoint(x, y);
  };

  return {
    ref: (node: HTMLDivElement) => {
      el = node;
    },
    onPointerDown: (e: PointerEvent) => {
      e.preventDefault();
      el?.setPointerCapture(e.pointerId);
      dragging = true;
      readPoint(e);
    },
    onPointerMove: (e: PointerEvent) => {
      // Insurance against lost pointer capture: no buttons down means no drag.
      if (dragging && e.buttons === 0) {
        dragging = false;
        return;
      }
      if (dragging) readPoint(e);
    },
    onPointerUp: () => {
      dragging = false;
    },
    onPointerCancel: () => {
      dragging = false;
    },
  };
}

/**
 * One numeric channel field. Holds a draft string while focused so partial
 * typing ("25" on the way to "255") never round-trips through the color.
 */
function ChannelField(props: { spec: ChannelSpec; value: number; onCommit: (n: number) => void }) {
  const [draft, setDraft] = createSignal<string | null>(null);
  const display = () => draft() ?? String(props.value);

  const commit = () => {
    const d = draft();
    if (d !== null) props.onCommit(Number(d));
    setDraft(null);
  };

  return (
    <label class="tweakers-color-field">
      <input
        type="text"
        inputmode="decimal"
        value={display()}
        onFocus={(e) => {
          setDraft(String(props.value));
          e.currentTarget.select();
        }}
        onInput={(e) => setDraft(e.currentTarget.value)}
        onBlur={commit}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            commit();
            e.currentTarget.blur();
          } else if (e.key === 'Escape') {
            e.stopPropagation();
            setDraft(null);
            e.currentTarget.blur();
          }
        }}
      />
      <span class="tweakers-color-field-label">{props.spec.label}</span>
    </label>
  );
}

function HexField(props: { value: string; alpha: boolean; onCommit: (hex: string) => void }) {
  const [draft, setDraft] = createSignal<string | null>(null);

  const commit = () => {
    const d = draft();
    if (d !== null) {
      const normalized = normalizeHex(d, props.alpha);
      if (normalized) props.onCommit(normalized);
    }
    setDraft(null);
  };

  return (
    <label class="tweakers-color-field tweakers-color-field-hex">
      <input
        type="text"
        spellcheck={false}
        value={(draft() ?? props.value).toUpperCase()}
        onFocus={(e) => {
          setDraft(props.value);
          e.currentTarget.select();
        }}
        onInput={(e) => setDraft(e.currentTarget.value)}
        onBlur={commit}
        onKeyDown={(e) => {
          if (e.key === 'Enter') {
            commit();
            e.currentTarget.blur();
          } else if (e.key === 'Escape') {
            e.stopPropagation();
            setDraft(null);
            e.currentTarget.blur();
          }
        }}
      />
      <span class="tweakers-color-field-label">HEX</span>
    </label>
  );
}

function PaletteSlot(props: {
  color: string | null;
  onSave: () => void;
  onApply: () => void;
  onClear: () => void;
}) {
  const [holding, setHolding] = createSignal(false);
  let timer: ReturnType<typeof setTimeout> | null = null;
  let origin: { x: number; y: number } | null = null;
  let fired = false;

  const cancelHold = () => {
    if (timer) clearTimeout(timer);
    timer = null;
    origin = null;
    setHolding(false);
  };

  onCleanup(cancelHold);

  return (
    <button
      class="tweakers-color-palette-slot"
      data-filled={String(props.color !== null)}
      data-holding={String(holding())}
      style={props.color ? { '--swatch-color': props.color } : undefined}
      title={props.color ? `${props.color.toUpperCase()} — click to apply, hold to clear` : 'Save current color'}
      onContextMenu={(e) => e.preventDefault()}
      onPointerDown={(e) => {
        // Always reset first: a new press is never a stale long-press echo.
        fired = false;
        if (!props.color) return;
        origin = { x: e.clientX, y: e.clientY };
        setHolding(true);
        timer = setTimeout(() => {
          fired = true;
          cancelHold();
          props.onClear();
        }, LONG_PRESS_MS);
      }}
      onPointerMove={(e) => {
        if (!origin) return;
        if (Math.hypot(e.clientX - origin.x, e.clientY - origin.y) > PALETTE_DRAG_CANCEL_PX) {
          cancelHold();
        }
      }}
      onPointerUp={cancelHold}
      onPointerLeave={cancelHold}
      onPointerCancel={cancelHold}
      onClick={() => {
        // A completed long-press consumes the click that follows it.
        if (fired) {
          fired = false;
          return;
        }
        if (props.color) props.onApply();
        else props.onSave();
      }}
    />
  );
}

export function ColorPickerPanel(props: ColorPickerPanelProps) {
  const alpha = () => props.alpha ?? false;
  const palette = () => props.palette ?? false;

  const initialRgba = parseHex(props.value);
  const [hsva, setHsva] = createSignal<HSVA>(initialRgba ? rgbToHsv(initialRgba) : BLACK);
  const [format, setFormat] = createSignal<ColorFormat>(stickyFormat);
  const [slots, setSlots] = createSignal<PaletteSlots>(props.palette ? loadPalette() : emptyPalette());
  let lastEmitted = props.value;

  // External value changes (preset restore, config edit) re-derive the working
  // state; our own emissions don't, so the SV thumb keeps hue/sat at black/white.
  createEffect(() => {
    const value = props.value;
    if (value === lastEmitted) return;
    lastEmitted = value;
    const rgba = parseHex(value);
    if (rgba) setHsva(rgbToHsv(rgba));
  });

  createEffect(() => {
    if (!palette()) return;
    onCleanup(subscribePalette((s) => setSlots(s)));
  });

  const emit = (next: HSVA) => {
    setHsva(next);
    const hex = formatHex(hsvToRgb(next), alpha());
    lastEmitted = hex;
    props.onChange(hex);
  };

  const applyHex = (hex: string) => {
    const rgba = parseHex(hex);
    if (!rgba) return;
    const normalized = formatHex(rgba, alpha());
    setHsva(rgbToHsv(rgba));
    lastEmitted = normalized;
    props.onChange(normalized);
  };

  const svDrag = createAreaDrag((x, y) => emit({ ...hsva(), s: x, v: 1 - y }));
  const hueDrag = createAreaDrag((x) => emit({ ...hsva(), h: Math.min(x * 360, 359.999) }));
  const alphaDrag = createAreaDrag((x) => emit({ ...hsva(), a: x }));

  const rgba = () => hsvToRgb(hsva());
  const opaqueHex = () => formatHex(rgba(), false);
  const currentHex = () => formatHex(rgba(), alpha());
  const channelSpecs = () =>
    format() === 'hex' ? [] : getChannels(format() as Exclude<ColorFormat, 'hex'>, alpha());
  const channelValues = () =>
    format() === 'hex' ? [] : rgbaToChannels(rgba(), format() as Exclude<ColorFormat, 'hex'>, alpha());

  const commitChannel = (index: number, n: number) => {
    const next = [...channelValues()];
    next[index] = n;
    const committed = channelsToRgba(next, format() as Exclude<ColorFormat, 'hex'>, alpha());
    const nextHsva = rgbToHsv(committed);
    // Hue/saturation are meaningless on grays; keep the current ones so the
    // SV thumb doesn't jump when a channel edit lands on black/white.
    if (nextHsva.s === 0) nextHsva.h = hsva().h;
    if (nextHsva.v === 0) nextHsva.s = hsva().s;
    emit(nextHsva);
  };

  return (
    <div class="tweakers-color-picker" style={{ '--picker-hue': String(hsva().h) }}>
      <div
        class="tweakers-color-sv"
        ref={svDrag.ref}
        onPointerDown={svDrag.onPointerDown}
        onPointerMove={svDrag.onPointerMove}
        onPointerUp={svDrag.onPointerUp}
        onPointerCancel={svDrag.onPointerCancel}
      >
        <div
          class="tweakers-color-sv-thumb"
          style={{ left: `${hsva().s * 100}%`, top: `${(1 - hsva().v) * 100}%`, background: opaqueHex() }}
        />
      </div>

      <div
        class="tweakers-color-slider tweakers-color-hue"
        ref={hueDrag.ref}
        onPointerDown={hueDrag.onPointerDown}
        onPointerMove={hueDrag.onPointerMove}
        onPointerUp={hueDrag.onPointerUp}
        onPointerCancel={hueDrag.onPointerCancel}
      >
        <div
          class="tweakers-color-slider-thumb"
          style={{ left: `${(hsva().h / 360) * 100}%`, background: `hsl(${hsva().h} 100% 50%)` }}
        />
      </div>

      <Show when={alpha()}>
        <div
          class="tweakers-color-slider tweakers-color-alpha tweakers-checker"
          ref={alphaDrag.ref}
          onPointerDown={alphaDrag.onPointerDown}
          onPointerMove={alphaDrag.onPointerMove}
          onPointerUp={alphaDrag.onPointerUp}
          onPointerCancel={alphaDrag.onPointerCancel}
        >
          <div
            class="tweakers-color-alpha-gradient"
            style={{ background: `linear-gradient(to right, transparent, ${opaqueHex()})` }}
          />
          <div
            class="tweakers-color-slider-thumb"
            style={{ left: `${hsva().a * 100}%`, background: opaqueHex(), opacity: Math.max(hsva().a, 0.15) }}
          />
        </div>
      </Show>

      <SegmentedControl
        options={FORMAT_OPTIONS}
        value={format()}
        onChange={(f) => {
          stickyFormat = f;
          setFormat(f);
        }}
      />

      <div class="tweakers-color-fields" data-format={format()}>
        <Show
          when={format() === 'hex'}
          fallback={
            <For each={channelSpecs()}>
              {(spec, i) => (
                <ChannelField spec={spec} value={channelValues()[i()]} onCommit={(n) => commitChannel(i(), n)} />
              )}
            </For>
          }
        >
          <HexField value={currentHex()} alpha={alpha()} onCommit={applyHex} />
          <Show when={alpha()}>
            <ChannelField
              spec={{ key: 'a', label: 'A', min: 0, max: 100, step: 1, precision: 0 }}
              value={opacityPercent(rgba())}
              onCommit={(n) => emit({ ...hsva(), a: Math.min(1, Math.max(0, n / 100)) })}
            />
          </Show>
        </Show>
      </div>

      <Show when={palette()}>
        <div class="tweakers-color-palette">
          <For each={Array.from({ length: PALETTE_SIZE }, (_, i) => i)}>
            {(i) => (
              <PaletteSlot
                color={slots()[i] ?? null}
                // Read the store at commit time — a 500ms hold is long enough for
                // another panel or tab to have rewritten the palette underneath.
                onSave={() => savePalette(loadPalette().map((s, j) => (j === i ? currentHex() : s)))}
                onApply={() => {
                  const saved = slots()[i];
                  if (saved) applyHex(saved);
                }}
                onClear={() => savePalette(loadPalette().map((s, j) => (j === i ? null : s)))}
              />
            )}
          </For>
        </div>
      </Show>
    </div>
  );
}

// src/svelte/components/ColorPickerPanel.svelte
<script module lang="ts">
  import type { ColorFormat } from 'tweakers/color-core';

  // The format choice follows the user across pickers within a session —
  // switching to OKLCH once shouldn't need repeating per control.
  let stickyFormat: ColorFormat = 'hex';
</script>

<script lang="ts">
  import { untrack } from 'svelte';
  import SegmentedControl from './SegmentedControl.svelte';
  import {
    parseHex,
    formatHex,
    normalizeHex,
    rgbToHsv,
    hsvToRgb,
    getChannels,
    rgbaToChannels,
    channelsToRgba,
    opacityPercent,
    emptyPalette,
    LONG_PRESS_MS,
    PALETTE_DRAG_CANCEL_PX,
    type HSVA,
    type ChannelSpec,
    type PaletteSlots,
  } from 'tweakers/color-core';
  import { loadPalette, savePalette, subscribePalette } from 'tweakers/color-palette-store';

  let { value, onChange, alpha = false, palette = false } = $props<{
    value: string;
    onChange: (value: string) => void;
    alpha?: boolean;
    palette?: boolean;
  }>();

  const FORMAT_OPTIONS: { value: ColorFormat; label: string }[] = [
    { value: 'hex', label: 'HEX' },
    { value: 'rgb', label: 'RGB' },
    { value: 'hsl', label: 'HSL' },
    { value: 'oklch', label: 'OKLCH' },
  ];

  const BLACK: HSVA = { h: 0, s: 0, v: 0, a: 1 };
  const HEX_ALPHA_SPEC: ChannelSpec = { key: 'a', label: 'A', min: 0, max: 100, step: 1, precision: 0 };

  const initialRgba = parseHex(untrack(() => value));
  let hsva = $state<HSVA>(initialRgba ? rgbToHsv(initialRgba) : BLACK);
  let format = $state<ColorFormat>(stickyFormat);
  let slots = $state<PaletteSlots>(untrack(() => palette) ? loadPalette() : emptyPalette());
  let lastEmitted = untrack(() => value);

  // External value changes (preset restore, config edit) re-derive the working
  // state; our own emissions don't, so the SV thumb keeps hue/sat at black/white.
  $effect(() => {
    if (value === lastEmitted) return;
    lastEmitted = value;
    const rgba = parseHex(value);
    if (rgba) hsva = rgbToHsv(rgba);
  });

  $effect(() => {
    if (!palette) return;
    return subscribePalette((s) => {
      slots = s;
    });
  });

  function emit(next: HSVA) {
    hsva = next;
    const hex = formatHex(hsvToRgb(next), alpha);
    lastEmitted = hex;
    onChange(hex);
  }

  function applyHex(hex: string) {
    const rgba = parseHex(hex);
    if (!rgba) return;
    const normalized = formatHex(rgba, alpha);
    hsva = rgbToHsv(rgba);
    lastEmitted = normalized;
    onChange(normalized);
  }

  /** Shared drag surface: pointer-capture + normalized 0–1 coordinates. */
  function areaDrag(onPoint: (x: number, y: number) => void) {
    let dragging = false;
    let el: HTMLElement | null = null;
    const readPoint = (e: PointerEvent) => {
      if (!el) return;
      const rect = el.getBoundingClientRect();
      const x = Math.min(1, Math.max(0, (e.clientX - rect.left) / rect.width));
      const y = Math.min(1, Math.max(0, (e.clientY - rect.top) / rect.height));
      onPoint(x, y);
    };
    return {
      onpointerdown: (e: PointerEvent) => {
        e.preventDefault();
        el = e.currentTarget as HTMLElement;
        el.setPointerCapture(e.pointerId);
        dragging = true;
        readPoint(e);
      },
      onpointermove: (e: PointerEvent) => {
        // Insurance against lost pointer capture: no buttons down means no drag.
        if (dragging && e.buttons === 0) {
          dragging = false;
          return;
        }
        if (dragging) readPoint(e);
      },
      onpointerup: () => {
        dragging = false;
      },
      onpointercancel: () => {
        dragging = false;
      },
    };
  }

  const svDrag = areaDrag((x, y) => emit({ ...hsva, s: x, v: 1 - y }));
  const hueDrag = areaDrag((x) => emit({ ...hsva, h: Math.min(x * 360, 359.999) }));
  const alphaDrag = areaDrag((x) => emit({ ...hsva, a: x }));

  const rgba = $derived(hsvToRgb(hsva));
  const opaqueHex = $derived(formatHex(rgba, false));
  const currentHex = $derived(formatHex(rgba, alpha));
  const channelSpecs = $derived(format === 'hex' ? [] : getChannels(format as Exclude<ColorFormat, 'hex'>, alpha));
  const channelValues = $derived(format === 'hex' ? [] : rgbaToChannels(rgba, format as Exclude<ColorFormat, 'hex'>, alpha));

  function commitChannel(index: number, n: number) {
    const next = [...channelValues];
    next[index] = n;
    const committed = channelsToRgba(next, format as Exclude<ColorFormat, 'hex'>, alpha);
    const nextHsva = rgbToHsv(committed);
    // Hue/saturation are meaningless on grays; keep the current ones so the
    // SV thumb doesn't jump when a channel edit lands on black/white.
    if (nextHsva.s === 0) nextHsva.h = hsva.h;
    if (nextHsva.v === 0) nextHsva.s = hsva.s;
    emit(nextHsva);
  }

  // One draft at a time (drafts are focus-bound); partial typing ("25" on the
  // way to "255") never round-trips through the color.
  let channelDraft = $state<{ id: string; text: string } | null>(null);
  let hexDraft = $state<string | null>(null);

  function commitChannelDraft(id: string, onCommit: (n: number) => void) {
    if (channelDraft?.id === id) onCommit(Number(channelDraft.text));
    channelDraft = null;
  }

  function commitHexDraft() {
    if (hexDraft !== null) {
      const normalized = normalizeHex(hexDraft, alpha);
      if (normalized) applyHex(normalized);
    }
    hexDraft = null;
  }

  // ── Palette long-press (only one slot can be held at a time) ──
  let holdingSlot = $state<number | null>(null);
  let holdTimer: ReturnType<typeof setTimeout> | null = null;
  let holdOrigin: { x: number; y: number } | null = null;
  let holdFired = false;

  function cancelHold() {
    if (holdTimer) clearTimeout(holdTimer);
    holdTimer = null;
    holdOrigin = null;
    holdingSlot = null;
  }

  function startHold(i: number, color: string | null, e: PointerEvent) {
    // Always reset first: a new press is never a stale long-press echo.
    holdFired = false;
    if (!color) return;
    holdOrigin = { x: e.clientX, y: e.clientY };
    holdingSlot = i;
    holdTimer = setTimeout(() => {
      holdFired = true;
      cancelHold();
      // Read the store at commit time — a 500ms hold is long enough for
      // another panel or tab to have rewritten the palette underneath.
      savePalette(loadPalette().map((s, j) => (j === i ? null : s)));
    }, LONG_PRESS_MS);
  }

  function moveHold(e: PointerEvent) {
    if (!holdOrigin) return;
    if (Math.hypot(e.clientX - holdOrigin.x, e.clientY - holdOrigin.y) > PALETTE_DRAG_CANCEL_PX) {
      cancelHold();
    }
  }

  function clickSlot(i: number, color: string | null) {
    // A completed long-press consumes the click that follows it.
    if (holdFired) {
      holdFired = false;
      return;
    }
    if (color) applyHex(color);
    else savePalette(loadPalette().map((s, j) => (j === i ? currentHex : s)));
  }

  $effect(() => {
    return () => cancelHold();
  });
</script>

{#snippet channelField(id: string, spec: ChannelSpec, val: number, onCommit: (n: number) => void)}
  <label class="tweakers-color-field">
    <input
      type="text"
      inputmode="decimal"
      value={channelDraft?.id === id ? channelDraft.text : String(val)}
      onfocus={(e) => {
        channelDraft = { id, text: String(val) };
        (e.currentTarget as HTMLInputElement).select();
      }}
      oninput={(e) => {
        channelDraft = { id, text: (e.currentTarget as HTMLInputElement).value };
      }}
      onblur={() => commitChannelDraft(id, onCommit)}
      onkeydown={(e) => {
        if (e.key === 'Enter') {
          commitChannelDraft(id, onCommit);
          (e.currentTarget as HTMLInputElement).blur();
        } else if (e.key === 'Escape') {
          e.stopPropagation();
          channelDraft = null;
          (e.currentTarget as HTMLInputElement).blur();
        }
      }}
    />
    <span class="tweakers-color-field-label">{spec.label}</span>
  </label>
{/snippet}

<div class="tweakers-color-picker" style:--picker-hue={hsva.h}>
  <div
    class="tweakers-color-sv"
    role="application"
    aria-label="Saturation and brightness"
    onpointerdown={svDrag.onpointerdown}
    onpointermove={svDrag.onpointermove}
    onpointerup={svDrag.onpointerup}
    onpointercancel={svDrag.onpointercancel}
  >
    <div
      class="tweakers-color-sv-thumb"
      style:left="{hsva.s * 100}%"
      style:top="{(1 - hsva.v) * 100}%"
      style:background={opaqueHex}
    ></div>
  </div>

  <div
    class="tweakers-color-slider tweakers-color-hue"
    role="application"
    aria-label="Hue"
    onpointerdown={hueDrag.onpointerdown}
    onpointermove={hueDrag.onpointermove}
    onpointerup={hueDrag.onpointerup}
    onpointercancel={hueDrag.onpointercancel}
  >
    <div
      class="tweakers-color-slider-thumb"
      style:left="{(hsva.h / 360) * 100}%"
      style:background="hsl({hsva.h} 100% 50%)"
    ></div>
  </div>

  {#if alpha}
    <div
      class="tweakers-color-slider tweakers-color-alpha tweakers-checker"
      role="application"
      aria-label="Opacity"
      onpointerdown={alphaDrag.onpointerdown}
      onpointermove={alphaDrag.onpointermove}
      onpointerup={alphaDrag.onpointerup}
      onpointercancel={alphaDrag.onpointercancel}
    >
      <div
        class="tweakers-color-alpha-gradient"
        style:background="linear-gradient(to right, transparent, {opaqueHex})"
      ></div>
      <div
        class="tweakers-color-slider-thumb"
        style:left="{hsva.a * 100}%"
        style:background={opaqueHex}
        style:opacity={Math.max(hsva.a, 0.15)}
      ></div>
    </div>
  {/if}

  <SegmentedControl
    options={FORMAT_OPTIONS}
    value={format}
    onChange={(f: string) => {
      stickyFormat = f as ColorFormat;
      format = f as ColorFormat;
    }}
  />

  <div class="tweakers-color-fields" data-format={format}>
    {#if format === 'hex'}
      <label class="tweakers-color-field tweakers-color-field-hex">
        <input
          type="text"
          spellcheck="false"
          value={(hexDraft ?? currentHex).toUpperCase()}
          onfocus={(e) => {
            hexDraft = currentHex;
            (e.currentTarget as HTMLInputElement).select();
          }}
          oninput={(e) => {
            hexDraft = (e.currentTarget as HTMLInputElement).value;
          }}
          onblur={commitHexDraft}
          onkeydown={(e) => {
            if (e.key === 'Enter') {
              commitHexDraft();
              (e.currentTarget as HTMLInputElement).blur();
            } else if (e.key === 'Escape') {
              e.stopPropagation();
              hexDraft = null;
              (e.currentTarget as HTMLInputElement).blur();
            }
          }}
        />
        <span class="tweakers-color-field-label">HEX</span>
      </label>
      {#if alpha}
        {@render channelField(
          'hex-a',
          HEX_ALPHA_SPEC,
          opacityPercent(rgba),
          (n) => emit({ ...hsva, a: Math.min(1, Math.max(0, n / 100)) })
        )}
      {/if}
    {:else}
      {#each channelSpecs as spec, i (`${format}-${spec.key}`)}
        {@render channelField(`${format}-${spec.key}`, spec, channelValues[i], (n) => commitChannel(i, n))}
      {/each}
    {/if}
  </div>

  {#if palette}
    <div class="tweakers-color-palette">
      {#each slots as slotColor, i (i)}
        {@const color = slotColor ?? null}
        <button
          class="tweakers-color-palette-slot"
          data-filled={String(color !== null)}
          data-holding={String(holdingSlot === i)}
          style:--swatch-color={color}
          title={color ? `${color.toUpperCase()} — click to apply, hold to clear` : 'Save current color'}
          oncontextmenu={(e) => e.preventDefault()}
          onpointerdown={(e) => startHold(i, color, e)}
          onpointermove={moveHold}
          onpointerup={cancelHold}
          onpointerleave={cancelHold}
          onpointercancel={cancelHold}
          onclick={() => clickSlot(i, color)}
        ></button>
      {/each}
    </div>
  {/if}
</div>
