// src/components/Folder.tsx
import { useState, useRef, useEffect, ReactNode } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ICON_PANEL, ICON_CHEVRON } from 'tweakers/icons';
import { Checkbox } from './Checkbox';

interface FolderProps {
  title: string;
  children: ReactNode;
  defaultOpen?: boolean;
  /** `false` renders a plain section header: no caret, no click-to-collapse, body always open. */
  collapsible?: boolean;
  isRoot?: boolean;
  inline?: boolean;
  onOpenChange?: (isOpen: boolean) => void;
  toolbar?: ReactNode;
  /** Root only — the tab bar, riding the panel header under the toolbar. */
  tabs?: ReactNode;
  /** One line of help for the section, revealed on hover over the header. */
  hint?: string;
  hintId?: string;
  /**
   * Root only — the panel declared `_enabled`, so the whole panel is a module:
   * the title carries the switch and the body goes away when it is off. Same
   * idiom as ModuleFolder, one level up.
   */
  enabled?: boolean;
  onEnabledChange?: (enabled: boolean) => void;
}

export function Folder({ title, children, defaultOpen = true, collapsible = true, isRoot = false, inline = false, onOpenChange, toolbar, tabs, hint, hintId, enabled, onEnabledChange }: FolderProps) {
  const [isOpen, setIsOpen] = useState(collapsible ? defaultOpen : true);
  const [isCollapsed, setIsCollapsed] = useState(collapsible ? !defaultOpen : false);
  const contentRef = useRef<HTMLDivElement>(null);
  const [contentHeight, setContentHeight] = useState<number | undefined>(undefined);
  const [windowHeight, setWindowHeight] = useState(typeof window !== 'undefined' ? window.innerHeight : 800);

  useEffect(() => {
    if (!isRoot) return;
    const onResize = () => setWindowHeight(window.innerHeight);
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  }, [isRoot]);

  // Track content height for explicit panel sizing (no height: 'auto')
  useEffect(() => {
    const el = contentRef.current;
    if (!el) return;
    const ro = new ResizeObserver(() => {
      if (isOpen) {
        const h = el.offsetHeight;
        setContentHeight(prev => prev === h ? prev : h);
      }
    });
    ro.observe(el);
    return () => ro.disconnect();
  }, [isOpen]);

  // A module panel's switch is the only thing that shows or hides its body —
  // the rows below the title belong to a feature that is either on or off.
  const isModule = isRoot && enabled !== undefined && onEnabledChange !== undefined;
  const bodyOpen = isOpen && (!isModule || enabled);

  const handleToggle = () => {
    if (!collapsible) return;
    if (inline && isRoot) return;
    const next = !isOpen;
    setIsOpen(next);
    if (next) {
      setIsCollapsed(false);
    } else {
      setIsCollapsed(true);
    }
    onOpenChange?.(next);
  };

  const folderContent = (
    <div ref={isRoot ? contentRef : undefined} className={`tweakers-folder ${isRoot ? 'tweakers-folder-root' : ''}`}>
      <div
        className={`tweakers-folder-header ${isRoot ? 'tweakers-panel-header' : ''} ${collapsible ? '' : 'tweakers-folder-header-static'}`}
        onClick={collapsible ? handleToggle : undefined}
        data-hint={hint ? 'true' : undefined}
        aria-describedby={hint ? hintId : undefined}
      >
        <div className="tweakers-folder-header-top">
          {isRoot ? (
            isOpen && (
              <div className="tweakers-folder-title-row">
                {isModule && (
                  <Checkbox
                    checked={enabled!}
                    onChange={onEnabledChange!}
                    label={title}
                  />
                )}
                <span className="tweakers-folder-title tweakers-folder-title-root">
                  {title}
                </span>
              </div>
            )
          ) : (
            <div className="tweakers-folder-title-row">
              <span className="tweakers-folder-title">
                {title}
              </span>
            </div>
          )}
          {!isRoot && toolbar && (
            <div className="tweakers-folder-toolbar" onClick={(e) => e.stopPropagation()}>
              {toolbar}
            </div>
          )}
          {isRoot && !inline && (
            <svg
              className="tweakers-panel-icon"
              viewBox="0 0 16 16"
              fill="none"
            >
              <path opacity="0.5" d={ICON_PANEL.path} fill="currentColor"/>
              {ICON_PANEL.circles.map((c, i) => (
                <circle key={i} cx={c.cx} cy={c.cy} r={c.r} fill="currentColor" stroke="currentColor" strokeWidth="1.25"/>
              ))}
            </svg>
          )}
          {!isRoot && collapsible && (
            <motion.svg
              className="tweakers-folder-icon"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.5"
              strokeLinecap="round"
              strokeLinejoin="round"
              initial={false}
              animate={{ rotate: isOpen ? 0 : 180 }}
              transition={{ type: 'spring', visualDuration: 0.35, bounce: 0.15 }}
            >
              <path d={ICON_CHEVRON} />
            </motion.svg>
          )}
        </div>

        {isRoot && toolbar && isOpen && (
          <div className="tweakers-panel-toolbar" onClick={(e) => e.stopPropagation()}>
            {toolbar}
          </div>
        )}

        {isRoot && tabs && isOpen && (
          <div className="tweakers-panel-tabs" onClick={(e) => e.stopPropagation()}>
            {tabs}
          </div>
        )}

        {hint && (
          <span className="tweakers-hint" id={hintId} role="tooltip">
            {hint}
          </span>
        )}
      </div>

      <AnimatePresence initial={false}>
        {bodyOpen && (
          <motion.div
            className="tweakers-folder-content"
            initial={isRoot ? undefined : { height: 0, opacity: 0 }}
            animate={isRoot ? undefined : { height: 'auto', opacity: 1 }}
            exit={isRoot ? undefined : { height: 0, opacity: 0 }}
            transition={isRoot ? undefined : { type: 'spring', visualDuration: 0.35, bounce: 0.1 }}
            style={isRoot ? undefined : { clipPath: 'inset(0 -20px)' }}
          >
            <div className="tweakers-folder-inner">{children}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );

  if (isRoot) {
    if (inline) {
      return (
        <div className="tweakers-panel-inner tweakers-panel-inline">
          {folderContent}
        </div>
      );
    }

    const panelStyle = isOpen
      ? { width: 280, height: contentHeight !== undefined ? Math.min(contentHeight + 10, windowHeight - 32) : 'auto' as const, borderRadius: 14, boxShadow: 'var(--tweak-shadow)', cursor: undefined as string | undefined, overflowY: 'auto' as const }
      : { width: 42, height: 42, borderRadius: '50%', boxSizing: 'border-box' as const, boxShadow: 'var(--tweak-shadow-collapsed)', overflow: 'hidden' as const, cursor: 'pointer' as const };

    return (
      <motion.div
        className="tweakers-panel-inner"
        style={panelStyle}
        onClick={!isOpen ? handleToggle : undefined}
        data-collapsed={isCollapsed}
        whileTap={!isOpen ? { scale: 0.9 } : undefined}
        transition={{ type: 'spring', visualDuration: 0.15, bounce: 0.3 }}
      >
        {folderContent}
      </motion.div>
    );
  }

  return folderContent;
}

// src/svelte/components/Folder.svelte
<script lang="ts">
  import { Spring } from 'svelte/motion';
  import { slide } from 'svelte/transition';

  import type { Snippet } from 'svelte';
  import { ICON_PANEL, ICON_CHEVRON } from 'tweakers/icons';
  import Checkbox from './Checkbox.svelte';

  let {
    title,
    defaultOpen = true,
    collapsible = true,
    isRoot = false,
    inline = false,
    onOpenChange,
    toolbar,
    children,
    hint,
    hintId,
    enabled = undefined,
    onEnabledChange = undefined,
  } = $props<{
    title: string;
    defaultOpen?: boolean;
    /** `false` renders a plain section header: no caret, no click-to-collapse, body always open. */
    collapsible?: boolean;
    isRoot?: boolean;
    inline?: boolean;
    onOpenChange?: (isOpen: boolean) => void;
    toolbar?: Snippet;
    children?: Snippet;
    /** One line of help for the section, revealed on hover over the header. */
    hint?: string;
    hintId?: string;
    /**
     * Root only — the panel declared `_enabled`, so the whole panel is a
     * module: the title carries the switch and the body goes away when it is
     * off. Same idiom as ModuleFolder, one level up.
     */
    enabled?: boolean;
    onEnabledChange?: (enabled: boolean) => void;
  }>();


  let isOpen = $state(collapsible ? defaultOpen : true);
  // A module panel's switch is the only thing that shows or hides its body —
  // the rows below the title belong to a feature that is either on or off.
  const isModule = $derived(isRoot && enabled !== undefined && onEnabledChange !== undefined);
  const bodyOpen = $derived(isOpen && (!isModule || !!enabled));
  let isCollapsed = $state(collapsible ? !defaultOpen : false);
  let contentHeight = $state<number | undefined>(undefined);

  let contentRef: HTMLDivElement | undefined;
  let panelRef: HTMLDivElement | undefined;
  let windowHeight = $state(typeof window !== 'undefined' ? window.innerHeight : 800);

  $effect(() => {
    if (!isRoot) return;
    const onResize = () => { windowHeight = window.innerHeight; };
    window.addEventListener('resize', onResize);
    return () => window.removeEventListener('resize', onResize);
  });

  const chevronRotation = new Spring(defaultOpen ? 0 : 180, { stiffness: 0.2, damping: 0.6 });
  const panelWidth = new Spring(defaultOpen ? 280 : 42, { stiffness: 0.2, damping: 0.62 });
  const panelHeight = new Spring(defaultOpen ? 220 : 42, { stiffness: 0.2, damping: 0.62 });
  const panelRadius = new Spring(defaultOpen ? 14 : 21, { stiffness: 0.2, damping: 0.62 });
  const panelScale = new Spring(1, { stiffness: 0.25, damping: 0.7 });

  $effect(() => {
    if (!isRoot || !contentRef || typeof ResizeObserver === 'undefined') return;

    const ro = new ResizeObserver(() => {
      if (!isOpen) return;
      const next = contentRef?.offsetHeight;
      if (!next) return;
      contentHeight = next;
    });

    ro.observe(contentRef);

    if (contentRef.offsetHeight > 0) {
      contentHeight = contentRef.offsetHeight;
    }

    return () => {
      ro.disconnect();
    };
  });

  $effect(() => {
    if (isRoot) return;
    chevronRotation.set(isOpen ? 0 : 180);
  });

  $effect(() => {
    if (!isRoot) return;

    const measured = contentHeight ?? panelRef?.getBoundingClientRect().height ?? 42;
    const nextHeight = isOpen ? Math.min(measured + 10, windowHeight - 32) : 42;

    panelWidth.set(isOpen ? 280 : 42);
    panelHeight.set(nextHeight);
    panelRadius.set(isOpen ? 14 : 21);
  });

  const handleToggle = () => {
    if (!collapsible) return;
    if (inline && isRoot) return;
    const next = !isOpen;
    isOpen = next;
    isCollapsed = !next;
    onOpenChange?.(next);
  };

  const handleCollapsedTapStart = () => {
    if (isOpen) return;
    (document.activeElement as HTMLElement | null)?.blur?.();
    panelScale.set(0.9);
  };

  const handleCollapsedTapEnd = () => {
    if (isOpen) return;
    panelScale.set(1);
  };

  const panelStyle = $derived(
    `width:${panelWidth.current}px;height:${panelHeight.current}px;border-radius:${panelRadius.current}px;` +
      `box-shadow:${isOpen ? 'var(--tweak-shadow)' : 'var(--tweak-shadow-collapsed)'};` +
      `cursor:${isOpen ? '' : 'pointer'};overflow:${isOpen ? 'hidden auto' : 'hidden'};` +
      `transform:scale(${panelScale.current});`
  );
</script>

{#if isRoot && inline}
  <div class="tweakers-panel-inner tweakers-panel-inline">
    <div bind:this={contentRef} class="tweakers-folder tweakers-folder-root">
      <div class="tweakers-folder-header tweakers-panel-header" onclick={(e) => { e.stopPropagation(); handleToggle(); }}>
        <div class="tweakers-folder-header-top">
          <div class="tweakers-folder-title-row">
            {#if isModule}
              <Checkbox checked={!!enabled} onChange={onEnabledChange!} label={title} />
            {/if}
            <span class="tweakers-folder-title tweakers-folder-title-root">{title}</span>
          </div>
        </div>

        <div class="tweakers-panel-toolbar" onclick={(e) => e.stopPropagation()}>
          {#if toolbar}{@render toolbar()}{/if}
        </div>
      </div>

      {#if bodyOpen}
      <div class="tweakers-folder-content">
        <div class="tweakers-folder-inner">
          {#if children}{@render children()}{/if}
        </div>
      </div>
      {/if}
    </div>
  </div>
{:else if isRoot}
  <div
    bind:this={panelRef}
    class="tweakers-panel-inner"
    data-collapsed={String(isCollapsed)}
    style={panelStyle}
    onpointerdown={handleCollapsedTapStart}
    onpointerup={handleCollapsedTapEnd}
    onpointercancel={handleCollapsedTapEnd}
    onpointerleave={handleCollapsedTapEnd}
    onclick={() => { if (!isOpen) handleToggle(); }}
  >
    <div bind:this={contentRef} class="tweakers-folder tweakers-folder-root">
      <div class="tweakers-folder-header tweakers-panel-header" onclick={(e) => { e.stopPropagation(); handleToggle(); }}>
        <div class="tweakers-folder-header-top">
          {#if isOpen}
            <div class="tweakers-folder-title-row">
              {#if isModule}
                <Checkbox checked={!!enabled} onChange={onEnabledChange!} label={title} />
              {/if}
              <span class="tweakers-folder-title tweakers-folder-title-root">{title}</span>
            </div>
          {/if}

          <svg class="tweakers-panel-icon" viewBox="0 0 16 16" fill="none">
            <path
              opacity="0.5"
              d={ICON_PANEL.path}
              fill="currentColor"
            />
            <circle cx={ICON_PANEL.circles[0].cx} cy={ICON_PANEL.circles[0].cy} r={ICON_PANEL.circles[0].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
            <circle cx={ICON_PANEL.circles[1].cx} cy={ICON_PANEL.circles[1].cy} r={ICON_PANEL.circles[1].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
            <circle cx={ICON_PANEL.circles[2].cx} cy={ICON_PANEL.circles[2].cy} r={ICON_PANEL.circles[2].r} fill="currentColor" stroke="currentColor" stroke-width="1.25" />
          </svg>
        </div>

        {#if isOpen}
          <div class="tweakers-panel-toolbar" onclick={(e) => e.stopPropagation()}>
            {#if toolbar}{@render toolbar()}{/if}
          </div>
        {/if}
      </div>

      {#if bodyOpen}
        <div class="tweakers-folder-content">
          <div class="tweakers-folder-inner">
            {#if children}{@render children()}{/if}
          </div>
        </div>
      {/if}
    </div>
  </div>
{:else}
  <div class="tweakers-folder">
    <div
      class="tweakers-folder-header {collapsible ? '' : 'tweakers-folder-header-static'}"
      onclick={collapsible ? handleToggle : undefined}
      data-hint={hint ? 'true' : undefined}
      aria-describedby={hint ? hintId : undefined}
    >
      <div class="tweakers-folder-header-top">
        <div class="tweakers-folder-title-row">
          <span class="tweakers-folder-title">{title}</span>
        </div>

        {#if collapsible}
        <svg
          class="tweakers-folder-icon"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="2.5"
          stroke-linecap="round"
          stroke-linejoin="round"
          style:transform={`rotate(${chevronRotation.current}deg)`}
        >
          <path d={ICON_CHEVRON} />
        </svg>
        {/if}
      </div>

      {#if hint}
        <span class="tweakers-hint" id={hintId} role="tooltip">{hint}</span>
      {/if}
    </div>

    {#if isOpen}
      <div class="tweakers-folder-content" style="clip-path: inset(0 -20px);" transition:slide={{ duration: 220 }}>
        <div class="tweakers-folder-inner">
          {#if children}{@render children()}{/if}
        </div>
      </div>
    {/if}
  </div>
{/if}
