// src/svelte/components/ListControl.svelte
<script lang="ts">
  import { ICON_GRIP, ICON_PLUS, ICON_TRASH } from '../../icons';
  import { parseListItemSchema, defaultListItemParams } from 'dialkit/store';
  import type { ListItemValue, ListItemType, DialEvent } from 'dialkit/store';
  import Folder from './Folder.svelte';
  import Slider from './Slider.svelte';
  import Toggle from './Toggle.svelte';
  import SelectControl from './SelectControl.svelte';
  import ColorControl from './ColorControl.svelte';
  import TextControl from './TextControl.svelte';

  let { label, value, itemTypes, addLabel, maxItems, onChange, onEvent } = $props<{
    label: string;
    value: ListItemValue[];
    itemTypes: Record<string, ListItemType>;
    addLabel?: string;
    maxItems?: number;
    onChange: (value: ListItemValue[]) => void;
    onEvent: (event: DialEvent) => void;
  }>();

  let picking = $state(false);

  // Drag-to-reorder. `armed` is set on handle mousedown and checked at dragstart
  // so dragging a slider never starts a reorder.
  let armed = -1;
  let dragIndex = $state<number | null>(null);
  let over = $state<{ index: number; after: boolean } | null>(null);

  const typeEntries = $derived(Object.entries(itemTypes) as [string, ListItemType][]);
  const atCapacity = $derived(maxItems != null && value.length >= maxItems);

  function addItem(type: string) {
    if (atCapacity || !itemTypes[type]) return;
    onChange([...value, { type, params: defaultListItemParams(itemTypes[type].schema) }]);
    onEvent({ kind: 'list', op: 'add', index: value.length, itemType: type });
  }

  function removeItem(index: number) {
    onChange(value.filter((_: ListItemValue, i: number) => i !== index));
    onEvent({ kind: 'list', op: 'remove', index });
  }

  function moveItem(from: number, to: number) {
    if (from === to || to < 0 || to >= value.length) return;
    const next = value.slice();
    const [moved] = next.splice(from, 1);
    next.splice(to, 0, moved);
    onChange(next);
    onEvent({ kind: 'list', op: 'move', from, to });
  }

  function setParam(index: number, key: string, v: number | boolean | string) {
    onChange(
      value.map((item: ListItemValue, i: number) =>
        i === index ? { ...item, params: { ...item.params, [key]: v } } : item
      )
    );
    onEvent({ kind: 'list', op: 'set', index });
  }

  function handleAdd() {
    if (typeEntries.length === 1) addItem(typeEntries[0][0]);
    else picking = !picking;
  }

  function onDragStart(e: DragEvent, index: number) {
    if (armed !== index) { e.preventDefault(); return; }
    if (e.dataTransfer) {
      e.dataTransfer.effectAllowed = 'move';
      e.dataTransfer.setData('text/plain', String(index));
    }
    dragIndex = index;
  }

  function onDragOver(e: DragEvent, index: number) {
    if (dragIndex === null) return;
    e.preventDefault();
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    const after = e.clientY > rect.top + rect.height / 2;
    if (!(over?.index === index && over.after === after)) over = { index, after };
  }

  function onDrop() {
    if (dragIndex !== null && over !== null) {
      let to = over.after ? over.index + 1 : over.index;
      if (dragIndex < to) to -= 1;
      moveItem(dragIndex, to);
    }
    armed = -1;
    dragIndex = null;
    over = null;
  }

  function onDragEnd() {
    armed = -1;
    dragIndex = null;
    over = null;
  }
</script>

<svelte:window onmouseup={() => (armed = -1)} />

<Folder title={label} defaultOpen>
  <div class="dialkit-list-items" ondragover={(e) => e.preventDefault()} ondrop={onDrop} role="list">
    {#each value as item, index (index)}
      {@const type = itemTypes[item.type]}
      {#if type}
        {@const fields = parseListItemSchema(type.schema)}
        <div
          class="dialkit-list-item"
          draggable="true"
          role="listitem"
          data-dragging={dragIndex === index ? 'true' : undefined}
          data-over={over?.index === index ? (over.after ? 'after' : 'before') : undefined}
          ondragstart={(e) => onDragStart(e, index)}
          ondragover={(e) => onDragOver(e, index)}
          ondragend={onDragEnd}
        >
          <div class="dialkit-list-item-head">
            <span class="dialkit-list-item-title">{type.label}</span>
            <div class="dialkit-list-item-actions">
              <button
                type="button"
                class="dialkit-list-drag"
                aria-label="Drag to reorder"
                onmousedown={() => (armed = index)}
              >
                <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                  {#each ICON_GRIP as c}
                    <circle cx={c.cx} cy={c.cy} r="1.5" />
                  {/each}
                </svg>
              </button>
              <button
                type="button"
                class="dialkit-list-icon-btn dialkit-list-remove"
                onclick={() => removeItem(index)}
                aria-label={`Remove ${type.label}`}
              >
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
                  {#each ICON_TRASH as d}
                    <path {d} />
                  {/each}
                </svg>
              </button>
            </div>
          </div>

          {#if fields.length > 0}
            <div class="dialkit-list-item-fields">
              {#each fields as field (field.key)}
                {#if field.kind === 'slider'}
                  <Slider
                    label={field.label}
                    value={item.params[field.key] as number}
                    min={field.min}
                    max={field.max}
                    step={field.step}
                    onChange={(v) => setParam(index, field.key, v)}
                  />
                {:else if field.kind === 'toggle'}
                  <Toggle
                    label={field.label}
                    checked={item.params[field.key] as boolean}
                    onChange={(v) => setParam(index, field.key, v)}
                  />
                {:else if field.kind === 'select'}
                  <SelectControl
                    label={field.label}
                    value={item.params[field.key] as string}
                    options={field.options ?? []}
                    onChange={(v) => setParam(index, field.key, v)}
                  />
                {:else if field.kind === 'color'}
                  <ColorControl
                    label={field.label}
                    value={item.params[field.key] as string}
                    onChange={(v) => setParam(index, field.key, v)}
                  />
                {:else if field.kind === 'text'}
                  <TextControl
                    label={field.label}
                    value={item.params[field.key] as string}
                    placeholder={field.placeholder}
                    onChange={(v) => setParam(index, field.key, v)}
                  />
                {/if}
              {/each}
            </div>
          {/if}
        </div>
      {/if}
    {/each}

    {#if value.length === 0 && !picking}
      <div class="dialkit-list-empty">No items yet</div>
    {/if}
  </div>

  {#if !atCapacity}
    <div class="dialkit-list-add">
      <button type="button" class="dialkit-list-add-btn" data-open={String(picking)} onclick={handleAdd}>
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d={ICON_PLUS} />
        </svg>
        <span>{addLabel ?? 'Add'}</span>
      </button>

      {#if typeEntries.length > 1}
        <div class="dialkit-list-picker" data-open={String(picking)}>
          <div class="dialkit-list-picker-inner">
            {#each typeEntries as [key, type] (key)}
              <button
                type="button"
                class="dialkit-list-picker-chip"
                onclick={() => { addItem(key); picking = false; }}
              >
                {type.label}
              </button>
            {/each}
          </div>
        </div>
      {/if}
    </div>
  {/if}
</Folder>

// src/components/ListControl.tsx
import { useRef, useState, useEffect } from 'react';
import { ICON_GRIP, ICON_PLUS, ICON_TRASH } from '../icons';
import { Folder } from './Folder';
import { Slider } from './Slider';
import { Toggle } from './Toggle';
import { SelectControl } from './SelectControl';
import { ColorControl } from './ColorControl';
import { TextControl } from './TextControl';
import {
  parseListItemSchema,
  defaultListItemParams,
  type ListItemValue,
  type ListItemType,
  type ListField,
  type DialEvent,
} from '../store/DialStore';

interface ListControlProps {
  label: string;
  value: ListItemValue[];
  itemTypes: Record<string, ListItemType>;
  addLabel?: string;
  maxItems?: number;
  onChange: (value: ListItemValue[]) => void;
  /** Structural signal for engines that bridge list ops imperatively. */
  onEvent: (event: DialEvent) => void;
}

type Scalar = number | boolean | string;

/** Renders one list-item field by reusing the matching primitive control. */
function FieldControl({ field, value, onChange }: { field: ListField; value: Scalar; onChange: (v: Scalar) => void }) {
  switch (field.kind) {
    case 'slider':
      return <Slider label={field.label} value={value as number} min={field.min} max={field.max} step={field.step} onChange={onChange} />;
    case 'toggle':
      return <Toggle label={field.label} checked={value as boolean} onChange={onChange} />;
    case 'select':
      return <SelectControl label={field.label} value={value as string} options={field.options ?? []} onChange={onChange} />;
    case 'color':
      return <ColorControl label={field.label} value={value as string} onChange={onChange} />;
    case 'text':
      return <TextControl label={field.label} value={value as string} onChange={onChange} placeholder={field.placeholder} />;
    default:
      return null;
  }
}

export function ListControl({ label, value, itemTypes, addLabel, maxItems, onChange, onEvent }: ListControlProps) {
  const idCounter = useRef(0);
  const mkId = () => `li-${idCounter.current++}`;
  // One stable key per row so the right node animates/reconciles on remove and
  // reorder. Handlers keep `ids` in lockstep with `value`.
  const [ids, setIds] = useState<string[]>(() => value.map(mkId));
  const [picking, setPicking] = useState(false);

  // Drag-to-reorder. The row is only draggable once a drag starts from the
  // handle (armedRef), so dragging a slider never reorders the list.
  const armedRef = useRef<number | null>(null);
  const [dragIndex, setDragIndex] = useState<number | null>(null);
  const [over, setOver] = useState<{ index: number; after: boolean } | null>(null);

  // Reconcile only when the array length changes outside our handlers (preset
  // load / reset). The guard converges, so React's adjust-state-on-render is safe.
  if (ids.length !== value.length) {
    setIds((cur) => value.map((_, i) => cur[i] ?? mkId()));
  }

  // A press on the handle that doesn't become a drag must disarm the row.
  useEffect(() => {
    const disarm = () => { armedRef.current = null; };
    window.addEventListener('mouseup', disarm);
    return () => window.removeEventListener('mouseup', disarm);
  }, []);

  const typeEntries = Object.entries(itemTypes);
  const atCapacity = maxItems != null && value.length >= maxItems;

  const addItem = (type: string) => {
    if (atCapacity || !itemTypes[type]) return;
    const next = [...value, { type, params: defaultListItemParams(itemTypes[type].schema) }];
    setIds((cur) => [...cur, mkId()]);
    onChange(next);
    onEvent({ kind: 'list', op: 'add', index: next.length - 1, itemType: type });
  };

  const removeItem = (index: number) => {
    setIds((cur) => cur.filter((_, i) => i !== index));
    onChange(value.filter((_, i) => i !== index));
    onEvent({ kind: 'list', op: 'remove', index });
  };

  const moveItem = (from: number, to: number) => {
    if (from === to || to < 0 || to >= value.length) return;
    const reorder = <T,>(arr: T[]): T[] => {
      const out = arr.slice();
      const [moved] = out.splice(from, 1);
      out.splice(to, 0, moved);
      return out;
    };
    setIds(reorder);
    onChange(reorder(value));
    onEvent({ kind: 'list', op: 'move', from, to });
  };

  const setParam = (index: number, key: string, v: Scalar) => {
    onChange(value.map((item, i) => (i === index ? { ...item, params: { ...item.params, [key]: v } } : item)));
    onEvent({ kind: 'list', op: 'set', index });
  };

  const handleAdd = () => {
    if (typeEntries.length === 1) addItem(typeEntries[0][0]);
    else setPicking((p) => !p);
  };

  const onDrop = () => {
    if (dragIndex !== null && over !== null) {
      let to = over.after ? over.index + 1 : over.index;
      if (dragIndex < to) to -= 1; // account for the dragged row being removed first
      moveItem(dragIndex, to);
    }
    armedRef.current = null;
    setDragIndex(null);
    setOver(null);
  };

  return (
    <Folder title={label} defaultOpen>
      <div className="dialkit-list-items" onDragOver={(e) => e.preventDefault()} onDrop={onDrop}>
        {value.map((item, index) => {
          const type = itemTypes[item.type];
          if (!type) return null;
          const fields = parseListItemSchema(type.schema);
          const overState = over?.index === index ? (over.after ? 'after' : 'before') : undefined;
          return (
            <div
              key={ids[index]}
              className="dialkit-list-item"
              draggable
              data-dragging={dragIndex === index ? 'true' : undefined}
              data-over={overState}
              onDragStart={(e) => {
                if (armedRef.current !== index) { e.preventDefault(); return; }
                e.dataTransfer.effectAllowed = 'move';
                e.dataTransfer.setData('text/plain', String(index)); // Firefox needs payload
                setDragIndex(index);
              }}
              onDragOver={(e) => {
                if (dragIndex === null) return;
                e.preventDefault();
                const rect = e.currentTarget.getBoundingClientRect();
                const after = e.clientY > rect.top + rect.height / 2;
                setOver((o) => (o?.index === index && o.after === after ? o : { index, after }));
              }}
              onDragEnd={() => { armedRef.current = null; setDragIndex(null); setOver(null); }}
            >
              <div className="dialkit-list-item-head">
                <span className="dialkit-list-item-title">{type.label}</span>
                <div className="dialkit-list-item-actions">
                  <button
                    type="button"
                    className="dialkit-list-drag"
                    aria-label="Drag to reorder"
                    onMouseDown={() => { armedRef.current = index; }}
                  >
                    <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
                      {ICON_GRIP.map((c, i) => <circle key={i} cx={c.cx} cy={c.cy} r="1.5" />)}
                    </svg>
                  </button>
                  <button
                    type="button"
                    className="dialkit-list-icon-btn dialkit-list-remove"
                    onClick={() => removeItem(index)}
                    aria-label={`Remove ${type.label}`}
                  >
                    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
                      {ICON_TRASH.map((d, i) => <path key={i} d={d} />)}
                    </svg>
                  </button>
                </div>
              </div>
              {fields.length > 0 && (
                <div className="dialkit-list-item-fields">
                  {fields.map((field) => (
                    <FieldControl
                      key={field.key}
                      field={field}
                      value={item.params[field.key]}
                      onChange={(v) => setParam(index, field.key, v)}
                    />
                  ))}
                </div>
              )}
            </div>
          );
        })}

        {value.length === 0 && !picking && <div className="dialkit-list-empty">No items yet</div>}
      </div>

      {!atCapacity && (
        <div className="dialkit-list-add">
          <button type="button" className="dialkit-list-add-btn" data-open={String(picking)} onClick={handleAdd}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d={ICON_PLUS} />
            </svg>
            <span>{addLabel ?? 'Add'}</span>
          </button>

          {typeEntries.length > 1 && (
            <div className="dialkit-list-picker" data-open={String(picking)}>
              <div className="dialkit-list-picker-inner">
                {typeEntries.map(([key, type]) => (
                  <button
                    key={key}
                    type="button"
                    className="dialkit-list-picker-chip"
                    onClick={() => { addItem(key); setPicking(false); }}
                  >
                    {type.label}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </Folder>
  );
}
