// src/solid/components/Module.tsx
import { JSX } from 'solid-js';
import { SegmentedControl } from './SegmentedControl';

interface ModuleProps {
  title: string;
  enabled: boolean;
  onEnabledChange: (enabled: boolean) => void;
  children?: JSX.Element;
}

const ENABLE_OPTIONS = [
  { value: 'off' as const, label: 'Off' },
  { value: 'on' as const, label: 'On' },
];

/**
 * A titled module whose header carries an enable switch — for parameter
 * blocks that turn on/off as a unit. The switch doubles as the expand
 * control: disabling collapses the body away with a smooth height transition.
 */
export function Module(props: ModuleProps) {
  return (
    <div class="dialkit-module">
      <div class="dialkit-module-header">
        <span class="dialkit-module-title">{props.title}</span>
        <div class="dialkit-module-switch">
          <SegmentedControl
            options={ENABLE_OPTIONS}
            value={props.enabled ? 'on' : 'off'}
            onChange={(v) => props.onEnabledChange(v === 'on')}
          />
        </div>
      </div>

      <div class="dialkit-module-collapse" data-open={props.enabled}>
        <div class="dialkit-module-collapse-clip">
          <div class="dialkit-module-inner">{props.children}</div>
        </div>
      </div>
    </div>
  );
}

// src/components/Module.tsx
import { ReactNode } from 'react';
import { SegmentedControl } from './SegmentedControl';

interface ModuleProps {
  title: string;
  /** Whether the module is on. The Off/On switch is the expand control:
   *  off collapses the body away, on reveals it. */
  enabled: boolean;
  onEnabledChange: (enabled: boolean) => void;
  children: ReactNode;
}

const ENABLE_OPTIONS = [
  { value: 'off' as const, label: 'Off' },
  { value: 'on' as const, label: 'On' },
];

/**
 * A titled module whose header carries an enable switch — for parameter
 * blocks that turn on/off as a unit (synth layers, effect sends, optional
 * feature groups). The switch doubles as the expand control: disabling
 * collapses the body away with a smooth height transition.
 */
export function Module({ title, enabled, onEnabledChange, children }: ModuleProps) {
  return (
    <div className="dialkit-module">
      <div className="dialkit-module-header">
        <span className="dialkit-module-title">{title}</span>
        <div className="dialkit-module-switch">
          <SegmentedControl
            options={ENABLE_OPTIONS}
            value={enabled ? 'on' : 'off'}
            onChange={(v) => onEnabledChange(v === 'on')}
          />
        </div>
      </div>

      <div className="dialkit-module-collapse" data-open={enabled}>
        <div className="dialkit-module-collapse-clip">
          <div className="dialkit-module-inner">{children}</div>
        </div>
      </div>
    </div>
  );
}
